### ISSUE TITLE
Bulletvpn add request 

### ISSUE THREAD

**Issue by bijfy** [haugene/vpn-configs-contrib#107]
### Do you have the latest provider files?

- [X] I have checked that the provider are the latest

### Have you tested the provider files?

- [X] I have tested the provider files

### Can you create a PR for this config?

- [x] I can create a PR for this

### Provider details

Please add Bulletvpn in repo

### Anything else?

.

**Comment by pkishino** [comment]
Please create a PR or at least provide the provider files here.. without neither nothing will happen

**Comment by bijfy** [comment]
Hi here are the all openvpn configuration files for bulletvpn   https://www.bulletvpn.com/account/download/BulletVPN-OpenVPN.zip

**Comment by pkishino** [comment]
Thanks for the PR
