### ISSUE TITLE
Configuration update requirements for OVPN

### ISSUE THREAD

**Issue by derekcentrico** [haugene/vpn-configs-contrib#129]
### Do you have the latest provider files?

- [X] I have checked that the provider are the latest

### Have you tested the provider files?

- [X] I have tested the provider files

### Can you create a PR for this config?

- [ ] I can create a PR for this

### Provider details

Please let me know how you would like to document the new configuration flags and options for OVPN.

Users will need to define these based upon available OVPN files:

OVPN_CITY
OVPN_COUNTRY
OVPN_PROTOCOL (tcp vs. udp)
OVPN_CONNECTION (standard vs. multihop)

For instance, this is one of the configurations:

OVPN_CITY=chicago
OVPN_COUNTRY=us
OVPN_PROTOCOL=udp
OVPN_CONNECTION=multihop

Happy to assist with direction to be the most efficient to all.

**Comment by pkishino** [comment]
I believe this is covered here https://haugene.github.io/docker-transmission-openvpn/provider-specific/#ovpn
