### ISSUE TITLE
Port Forwarding with mullvad

### ISSUE THREAD

**Issue by sixhobbits** [haugene/vpn-configs-contrib#15]
## Before creating this request I have:

**REQUIRED**
- [X] Searched for similar [provider requests][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the request as possible
- [X] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
mullvad
```

### Where are the configs?

**REQUIRED**
```txt
https://mullvad.net/en/account/#/openvpn-config/
```
### Additional context

*Optional*

```txt
Similar to https://mullvad.net/en/account/#/openvpn-config/, I don't quite understand how to get port forwarding
 to work with mullvad. Transmission reports the port as "closed". Mullvad offers port forwarding, but on demand 
and via a random port only, so it would be nice to pass this in with the docker run command somehow? 
Happy to help with documenting it if someone can point me in the right direction.
```

**Comment by pkishino** [comment]
Do you generate a port in mullvad? In that case you can just update the port in the GUI for now, no?
Otherwise, yeah, someone could probably create a script for this and inject it.. look at some of the other providers that have such a script

**Comment by sixhobbits** [comment]
Ah, looks like I jumped the gun. I thought putting it in the GUI didn't work as it was still reporting closed and the issue I linked to said it didn't, but I gave it some time and it looks like it's working now.

Thanks for the pointers and hopefully my impatience helps someone else with the same issue down the road!
