### ISSUE TITLE
Surfshark config names broken

### ISSUE THREAD

**Issue by timw** [haugene/vpn-configs-contrib#150]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

OPENVPN_PROVIDER=surfshark
OPENVPN_CONFIG=us-lax_udp

### Current Behavior

The current surfshark config files have not had the `.prod.surfshark.com` part of the name removed, which historically was done.

### Expected Behavior

`.prod.surfshark.com` should not be present in the config file names.

### How have you tried to solve the problem?

This can be worked around by specifying the new config file name.
The git log indicates this change was not necessarily intentional, so raising as an issue to get a determination one way or the other.

### Log output

Supplied config us-lax_udp.ovpn could not be found.
Your options for this provider are:
-------8<---------
us-lax.prod.surfshark.com_tcp.ovpn
us-lax.prod.surfshark.com_udp.ovpn
-------8<---------

### Environment

```markdown
- OS: Synology Diskstation
- Docker:
```

### Anything else?

In 6a329b7c89cec08445e12619adb597ea5cb78a03, the script that updated the surfshark config files (to remove `.prod.surfshark.com`  from the file names, among other tweaks) was removed.

This was ostensibly done with a comment of:

> * Extended script updating surfshark configs.
>
> * Renamed surshark script to be consistent with others.

This doesn't seem to match the actual commit, which removed the script.

In the subsequent update of the surfshark configs in 647712c3d72e75e46fd1d642b6d578b87b6b26f0, the config files are committed with raw names, and thus any config using the previous abbreviated names breaks.

**Comment by timw** [comment]
@jake-melikov - can you comment on the intent of 6a329b7?

**Comment by jake-melikov** [comment]
@timw 

> This doesn't seem to match the actual commit, which removed the script.

The commit removed the `openvpn/surfshark/adjustSurfsharkConfigs.sh` script but added `openvpn/surfshark/updateConfigs.sh`.
