### ISSUE TITLE
Update PrivateVPN ovpn

### ISSUE THREAD

**Issue by short-circuit** [haugene/vpn-configs-contrib#16]
## Before creating this request I have:

**REQUIRED**
- [x] Searched for similar [provider requests][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the request as possible
- [x] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
PRIVATEVPN
```

### Where are the configs?

**REQUIRED**

[PrivateVPN-TUN-CBC.zip](https://github.com/haugene/vpn-configs-contrib/files/6560809/PrivateVPN-TUN-CBC.zip)

### Additional context

*Optional*

``` Hardcoded IP address needs to be changed or DNS resolving must be used. For example: Stockholm IP Changed from 193.180.119.2 to 45.130.87.9```

EDIT:
> For anyone waiting for this to be resolved:
> Use the ovpn files with the docker container in CUSTOM provider mode.

**Comment by short-circuit** [comment]
For anyone waiting for this to be resolved:
Use the ovpn files with the docker container in CUSTOM provider mode.

**Comment by macgrubr** [comment]
Is there a trick to using Custom provider mode?  I attempt to use it but it will switch to another provider after i save.  Not sure if i need to edit the config manually or not.

**Comment by short-circuit** [comment]
> 
> 
> Is there a trick to using Custom provider mode? I attempt to use it but it will switch to another provider after i save. Not sure if i need to edit the config manually or not.

Just follow the guide to use single custom ovpn files:
[https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_local_single_ovpn_file_from_provider](https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_local_single_ovpn_file_from_provider )

I only use one ovpn since not all profiles permit port forwarding. In case you can also use a [custom set of ovpn profiles](https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_local_set_of_ovpn_files_from_provider)

**Comment by macgrubr** [comment]
Thank you!

**Comment by pkishino** [comment]
can I ask where you got those ovpn files from? I also use Privatevpn but have a custom profile with them..
When I check privatevpn support pages I find all kinds of zip packages..

**Comment by pkishino** [comment]
Also, there is an updatescript for PrivateVpn that fetches the latest from https://privatevpn.com/client/PrivateVPN-TUN.zip
so not sure why this is needed

**Comment by short-circuit** [comment]
> 
> 
> can I ask where you got those ovpn files from? I also use Privatevpn but have a custom profile with them..
> When I check privatevpn support pages I find all kinds of zip packages..

Got it directly from support as the ones on the website are from 2019. But if the ones from the website are also domain based, there should be no problem in using those instead in custom provider mode.



> 
> 
> Also, there is an updatescript for PrivateVpn that fetches the latest from https://privatevpn.com/client/PrivateVPN-TUN.zip
> so not sure why this is needed

Could you link the updatescript? Never seen that and it would obviously simplify everything, but it does not seem to exist in my container. Or is there another way to activate it?

I only noticed that the PrivatVPN ovpn addresses are outdated in this repo, so suggested the edit to it.
If I am wrong, you can obviously get this issue closed 👍👍

**Comment by pkishino** [comment]
here
https://github.com/haugene/vpn-configs-contrib/tree/main/openvpn/privatevpn
updateConfigs.sh
this should be used by the main dev branch currently until this feature is added to master..

**Comment by short-circuit** [comment]
> 
> 
> here
> https://github.com/haugene/vpn-configs-contrib/tree/main/openvpn/privatevpn
> updateConfigs.sh
> this should be used by the main dev branch currently until this feature is added to master..

Ok so if I understand it correctly, the ovpn files are not actually being updated in this repo, but the script takes care of this at container runtime and checks the latest configuration on container start?
In that case, my container is unable to parse the new configurations of PrivateVPN because they retain the old IP addresses or are unable to do the DNS requests.

Here is a log of the non working container with provider PrivateVPN:
```log
Starting container with revision: e003c0639f287468c10cae9480b6993e68ff1392,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: PRIVATEVPN,
Running with VPN_CONFIG_SOURCE auto,
No bundled config script found for PRIVATEVPN. Defaulting to external config,
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.195sQksUlQ,
Extracting configs to /tmp/tmp.uVKc7ID8Tq,
Found configs for PRIVATEVPN in /tmp/tmp.uVKc7ID8Tq/vpn-configs-contrib-main/openvpn/privatevpn, will replace current content in /etc/openvpn/privatevpn,
Cleanup: deleting /tmp/tmp.195sQksUlQ and /tmp/tmp.uVKc7ID8Tq,
Starting OpenVPN using config SE Stockholm.ovpn,
Modifying /etc/openvpn/privatevpn/SE Stockholm.ovpn for best behaviour in this container,
Modification: Point auth-user-pass option to the username/password file,
Modification: Change ca certificate path,
Modification: Change ping options,
Setting OpenVPN credentials...,
enabling firewall,
Firewall is active and enabled on system startup,
allowing 9520 through the firewall,
Rule added,
allowing 192.168.32.1 through the firewall to port 9091,
Rule added,
adding route to local network xxxxxx via 192.168.32.1 dev eth0,
allowing xxxxxx through the firewall to port 9091,
Rule added,
Mon May 31 10:52:44 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 27 2021,
Mon May 31 10:52:44 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10,
Mon May 31 10:52:44 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Mon May 31 10:52:44 2021 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication,
Mon May 31 10:52:44 2021 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication,
Mon May 31 10:52:44 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]193.180.119.2:1194,
Mon May 31 10:52:44 2021 Socket Buffers: R=[212992->212992] S=[212992->212992],
Mon May 31 10:52:44 2021 UDP link local: (not bound),
Mon May 31 10:52:44 2021 UDP link remote: [AF_INET]193.180.119.2:1194,
Mon May 31 10:53:44 2021 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Mon May 31 10:53:44 2021 SIGTERM[soft,ping-exit] received, process exiting,
```
This is from the dev docker image.
I can't really pinpoint where the script is supposed to run since it says that it does not have any bundled scripts. Or do I have to use the custom scripts option of the container and manually run it?

As can be seen from the logs, it tries to always use previous IP addresses but never tries to get new ones even when it fails. But this might be an issue with the `transmission-openvpn` image then.

I also have UFW enabled in the container, can this cause the issue of the script or the retrieving of new IPs to fail?

**Comment by pkishino** [comment]
Hmm, I haven’t used the script myself, just a quick look were I thought it
would run during startup and replace config.. I’ll take a look tomorrow and
see what I can do.
There is another post on the main report regarding dns problems with ufw
turned on, think we’re still looking for a workaround. Most likely just a
route that needs adding

**Comment by short-circuit** [comment]
Great, let me know if you need more logs or if I can test anything to help close this issue!

**Comment by pkishino** [comment]
ok, so based on this:
https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/nordvpn/configure-openvpn.sh
could easily create one of those configure-openvpn.sh scripts that just calls the updateConfigs.sh before openvpn starts.
Also,
you could try the script here
https://github.com/haugene/docker-transmission-openvpn/issues/1817#issuecomment-846703736
but modify this accordingly.. ie.. just add the 53 route as a try and then close it once established or such..to prevent dns leaking.
bit busy to do the work now but let's see

**Comment by short-circuit** [comment]
Ok, so I have been playing around with the scripts a bit by creating a custom script that runs on container start (over the discovered `configure-openvpn.sh`). The existing `updateScripts.sh` cannot work currently for the simple reason that `xargs` does not have the delimiter `-d` option in alpine linux, which the `transmission-openvpn` is based on currently. Even by simply trying to download the archive and using its contents with some fixes by the script, the container continues to crash on boot with some key values not being recognized by OpenVPN. 
Haven't tried the `uwf` way yet.

**Comment by Zeelia** [comment]
Hello!
Just wanted to chime in and say that I'm also using PrivateVPN, and just got off the chat with their support team. 
The OpenVPN config files which they are offering (at least at https://privatevpn.com/support/getting-started/miscellaneous/openvpn/openvpn-configurations-files) are not yet updated to reflect the new hosts. 
I don't know if the updatescript fetches the same config files (which are not updated by PrivateVPN).

The support team told me to use hostnames instead of IP addresses. In my case, I want to connect to SE Stockholm and was trying to connect to 193.180.119.2. This IP is configured in the old OpenVPN config files by PrivateVPN, and also in transmission-openvpn. The new IP which **needs** be used is 45.130.87.3. However, the support team told me that the IP could change (rarely, once every 2 years if the IP has been abused), and therefore, hostname (se-sto.pvdata.host) should be used instead. 

Additionally, the support team said that they were not currently thinking about updating the OpenVPN config files to reflect the changes (which is strange!)

**Comment by pkishino** [comment]
The ovpn files used in the report are all using host  names afaik..
I linked the script above so you can check the files manually by
downloading them.
Also, please check using dev branch as that’s built on Ubuntu base which we
will be going back to with next release

**Comment by macgrubr** [comment]
Hello - I am curious if the problem with PrivateVPN will be fixed at all or if it already has?  I use Unraid and noticed there was an update to the package but nothing has changed.  It looks like it is still trying to connect to the old IP.   Since i am using Unraid I am not sure if it pulls the latest version from Github or if it grabs it from some other repository that lags behind. 

I am a newbie when it comes to modifying configs or having to do the work in the console so I am having a hard time understanding how to implement some of the fixes mentioned above.   Trying to get the custom mode to work with my own .opvn files seems like the easiest fix but have not had much luck.

This package was great for a beginner like me since it already was set to work with PrivateVPN and I knew enough to get it working.     If I cannot get this package working again, does anyone have any advice or recommendations for a torrent client with VPN that I could use considering I am using Unraid?  I am hoping to avoid spinning up a Windows VM since that is overkill and uses way to much resources. 

Any ideas or suggestions would be appreciated, thanks everyone!

**Comment by Zeelia** [comment]
I agree with @macgrubr, the config files don't seem to be updated. I tried downloading the PrivateVPN-TUN.zip package you linked @pkishino, but the config files still seem to use the old IP addresses. The repository also doesn't seem to be updated.

@macgrubr, what I did to temporary solve this issue, is to recreate my docker container, but using a local .ovpn file for PrivateVPN according to the guide at https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_local_single_ovpn_file_from_provider
The .ovpn file I am using is a copy from the repository (any file from https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/privatevpn), but I replaced the IP address on the first line to the corresponding host name from https://privatevpn.com/serverlist/

I'm not certain how the configuration works on Unraid, but I got it working on my Ubuntu server by taking the steps described above. Maybe I can write a more detailed explanation if it's required -- let me know.

**Comment by pkishino** [comment]
Hmm, let me check later tonight regarding the hostnames.. should be a quick fix to replace the ips in that case

**Comment by pkishino** [comment]
was only the SE-Stockholm files that used ip, fixed that in latest commit..

**Comment by short-circuit** [comment]
> 
> 
> was only the SE-Stockholm files that used ip, fixed that in latest commit..


This issue has arised again. It is again using old the IP address and it is just crashing with error 143 now. Nothing else on logs. Since it isn't a custom provider, I suppose this should be working? Or has the structure completely changed with release 4.0?
