### ISSUE TITLE
please add cyberghostvpn to the container

### ISSUE THREAD

**Issue by e2950** [haugene/vpn-configs-contrib#171]
### Do you have the latest provider files?

- [X] I have checked that the provider are the latest

### Have you tested the provider files?

- [X] I have tested the provider files

### Can you create a PR for this config?

- [ ] I can create a PR for this

### Provider details

cyberghost
[transmission_openvpn(3).zip](https://github.com/haugene/vpn-configs-contrib/files/10298276/transmission_openvpn.3.zip)

**Comment by e2950** [comment]
also once cyberghost is added what do i do with the ca.crt client.crt and client.key files?

**Comment by pkishino** [comment]
from what I remember in the past, cyber-ghost has personal certificates which makes it harder to automate, hence I suggest you use the custom provider setup mentioned in the documentation
