### ISSUE TITLE
Update Fastest-VPN available servers

### ISSUE THREAD

**Issue by tyalie** [haugene/vpn-configs-contrib#172]
### Do you have the latest provider files?

- [X] I have checked that the provider are the latest

### Have you tested the provider files?

- [X] I have tested the provider files

### Can you create a PR for this config?

- [ ] I can create a PR for this

### Provider details

The config files for FastestVPN are severely outdated since a few weeks at least.

This is the current list of available UDP servers 

Country | City | DNS
-------|----|----
Australia | Sydney | au-02.jumptoserver.com
Australia | Sydney | au-01.jumptoserver.com
Austria | Wien | at-01.jumptoserver.com
Belgium | Brussel | bel-01.jumptoserver.com
Brazil | null | br3.jumptoserver.com
Brazil | null | br2.jumptoserver.com
Brazil | Joao Pessoa | br.jumptoserver.com
Bulgaria | Sofia | bg-01.jumptoserver.com
Canada | Montreal | ca-01.jumptoserver.com
Canada | Montreal | ca-02.jumptoserver.com
Colombia | Bogota | clmb.jumptoserver.com
Czech Republic | Prague | cz-01.jumptoserver.com
Denmark | null | dk-01.jumptoserver.com
Finland | Helsinki | fi.jumptoserver.com
Finland | Helsinki | fi2.jumptoserver.com
France | Paris | fr.jumptoserver.com
France | Paris | uk-dbl.jumptoserver.com
Germany | Frankfurt | de-01.jumptoserver.com
Germany | Dusseldorf | de-dus1.jumptoserver.com
Greece | Athina | grc.jumptoserver.com
Hong Kong | HK | hk.jumptoserver.com
Hungary | Budapest | hng.jumptoserver.com
India | Mumbai | in-vr.jumptoserver.com
India | Mumbai | in5.jumptoserver.com
India | null | in6.jumptoserver.com
India | Mumbai | in2.jumptoserver.com
Ireland | Dublin | ir.jumptoserver.com
Italy | Assago | it-stream.jumptoserver.com
Italy | milan | it-01.jumptoserver.com
Japan | Tokyo | jp-stream.jumptoserver.com
Japan | Tokyo | jp-02.jumptoserver.com
Japan | Tokyo | jp-01.jumptoserver.com
Luxembourg | null | lux1.jumptoserver.com
Malaysia | null | my.jumptoserver.com
Mexico | null | mx.jumptoserver.com
Netherlands | Amsterdam | nl-01.jumptoserver.com
Netherlands | null | nl.jumptoserver.com
Norway | Oslo | nr-01.jumptoserver.com
Poland | Gdansk | pl.jumptoserver.com
Portugal | Lisbon | pt.jumptoserver.com
Romania | Bucharest | ro-01.jumptoserver.com
Russia | Moscow | ru3.jumptoserver.com
Russia | Moscow | ru4.jumptoserver.com
Serbia | Belgrade | rs-01.jumptoserver.com
Singapore | null | sg-01.jumptoserver.com
Singapore | Singapore | sg-01.jumptoserver.com
Slovakia | Bratislava | svk.jumptoserver.com
South Korea | Seoul | kr.jumptoserver.com
Spain | Barcelona | es-01.jumptoserver.com
Sweden | Stockholm | se-01.jumptoserver.com
Switzerland | Zurich | ch-01.jumptoserver.com
Turkey | Izmir | tr.jumptoserver.com
UAE | Dubai | uae.jumptoserver.com
UK | London | uk-02.jumptoserver.com
UK | London | uk-01.jumptoserver.com
United Kingdom | Wolverhampton | uk-01.jumptoserver.com
United Kingdom | London | us-dbl1.jumptoserver.com
United Kingdom | London | uk-streaming.jumptoserver.com
USA | Dallas | us-dl.jumptoserver.com
USA | Miami | us-mia.jumptoserver.com
USA | Denver | us-dv1.jumptoserver.com
USA | Miami | us-mia.jumptoserver.com
USA | Atlanta | us-at.jumptoserver.com
USA | Los Angeles | us-la.jumptoserver.com
USA | Los Angeles | us-la2.jumptoserver.com
USA | Anchorage | nl-dbl.jumptoserver.com
USA | Dallas | us-stream2.jumptoserver.com
USA | null | us-ch.jumptoserver.com
USA | Ashburn | us-ash.jumptoserver.com
USA | Seattle | us-se1.jumptoserver.com

 Only the following config files still work
- `US-Seattle-UDP.ovpn`
- `US-Los.Angeles-UDP.ovpn`
- `US-Denver-UDP.ovpn`
- `US-Dallas-UDP.ovpn`
- `US-Atlanta-UDP.ovpn`
- `UAE-Dubai-UDP.ovpn`
- `Turkey-UDP.ovpn`
- `South.Korea-UDP.ovpn`
- `Portugal-UDP.ovpn`
- `Netherlands1-UDP.ovpn`
- `Mexico-UDP.ovpn`
- `Malaysia-UDP.ovpn`
- `Luxembourg-UDP.ovpn`
- `India2-UDP.ovpn`
- `Hong.Kong-UDP.ovpn`
- `Finland-UDP.ovpn`

**Comment by tyalie** [comment]
I presumably could do a PR, but I'm not fully sure where I can get the full ovpn files from. I've right now only compared the DNS entries.

**Comment by stratman71** [comment]
Latest ovpn files for fastestVpn are at https://support.fastestvpn.com/download/fastestvpn_ovpn/

Good luck!
