### ISSUE TITLE
Adding hotspotShield to providers

### ISSUE THREAD

**Issue by thenorman138** [haugene/vpn-configs-contrib#18]
I'm trying to get the docker-compose for this going in my portainer instance on my openMediaVault server, but I can't seem to get the .ovpn file structured to work correctly.

Can HotspotShield be added to the supported providers, please?

**Comment by vic1707** [comment]
> I'm trying to get the docker-compose for this going in my portainer instance on my openMediaVault server, but I can't seem to get the .ovpn file structured to work correctly.
> 
> Can HotspotShield be added to the supported providers, please?
@thenorman138 
If you can provide a bundle of the ovpn files I'm sure someone could try to help (to check the structure of the files, do not share your credentials).

**Comment by wopali8302** [comment]
[HOTSPOTSHIELD.zip](https://github.com/haugene/vpn-configs-contrib/files/7582913/HOTSPOTSHIELD.zip)
there you have it, with all the countries named
