### ISSUE TITLE
Windscribe is sunsetting current certificates on 20 July 2021

### ISSUE THREAD

**Issue by brossow** [haugene/vpn-configs-contrib#19]
## Before creating this request I have:

**REQUIRED**
- [X] Searched for similar [provider requests][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the request as possible
- [X] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
Windscribe
```

### Where are the configs?

**REQUIRED**
```txt
No download that I know of; they use a config generator, for which I believe there may be an existing scraper (see below).
```
### Additional context

*Optional*

```
Windscribe just gave notice that they are sunsetting their current certificates on 20th July, so the existing OVPN files will need to be updated. As far as I can tell there is no way to just download all of the OVPN files from them at once, but a scraper was mentioned by @wilmardo in [this PR](https://github.com/haugene/docker-transmission-openvpn/pull/1691). Hopefully that can be used to grab the new files.

From Windscribe: "We are sunsetting our OpenVPN certificate authority and beginning to phase out compression on July 20 2021 at 17:00 UTC. If you're using an OpenVPN version less than 2.4 you will need download new configurations and install them on July 20 2021 after 17:00 UTC as they no longer contain compression options and it is not possible to gracefully transition without doing this at the same time we perform maintenance."

Links:
[https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222](https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222)
[https://windscribe.com/getconfig/openvpn](https://windscribe.com/getconfig/openvpn)
```

**Comment by brossow** [comment]
Windscribe just gave notice that they are sunsetting their current certificates on 20th July, so the existing OVPN files will need to be updated. As far as I can tell there is no way to just download all of the OVPN files from them at once, but a scraper was mentioned by @wilmardo in [this PR](https://github.com/haugene/docker-transmission-openvpn/pull/1691). Hopefully that can be used to grab the new files.

**From Windscribe:** "We are sunsetting our OpenVPN certificate authority and beginning to phase out compression on July 20 2021 at 17:00 UTC. If you're using an OpenVPN version less than 2.4 you will need download new configurations and install them on July 20 2021 after 17:00 UTC as they no longer contain compression options and it is not possible to gracefully transition without doing this at the same time we perform maintenance."

**Links:**
* [https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222](https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222)
* [https://windscribe.com/getconfig/openvpn](https://windscribe.com/getconfig/openvpn)

**Comment by brossow** [comment]
As per the commits and PR above, I used the scraper from @wilmardo to get the new OVPN files and modified them to use the credentials file. I am not an expert and have not tested these. According to Windscribe, they should work now as-is for anyone using OpenVPN v2.4 or later but will only work for earlier versions after 20 July 2021 at 17:00 UTC. Someone who knows what they're doing needs to review this.

**Comment by pkishino** [comment]
Update config merged in

**Comment by Pherax** [comment]
I have the problems connected to this "resolved" issue. I see the error:

```
2021-08-05 20:10:40 VERIFY ERROR: depth=1, error=unable to get local issuer certificate: C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=Windscribe Node CA X2, serial=1
2021-08-05 20:10:40 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

```

but this should be solved by the update you guys performed. I have set my container version to "latest", removed the old container en reinstalled to the new (3.7) with no effect.

what can I do to fix this?

**Comment by Sanrax** [comment]
> I have the problems connected to this "resolved" issue. I see the error:
> 
> ```
> 2021-08-05 20:10:40 VERIFY ERROR: depth=1, error=unable to get local issuer certificate: C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=Windscribe Node CA X2, serial=1
> 2021-08-05 20:10:40 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
> ```
> 
> but this should be solved by the update you guys performed. I have set my container version to "latest", removed the old container en reinstalled to the new (3.7) with no effect.
> 
> I also tried to put a "new" .ovpn config in by setting the OPENVPN_CONFIG=default
> 
> `/transmission-vpn/transmission-home/Windscribe-Amsterdam-Tulip.ovpn:/etc/openvpn/custom/default.ovpn`
> 
> what can I do to fix this?

Same exact issue here. I'm getting a certificate error as well. Hopefully this gets fixed, for now I will attempt to use my own .ovpn file.

**Comment by Pherax** [comment]
@Sanrax I solved my issue by making a folder Windscribe2, add it to volume as 
`transmission-vpn/transmission-home/Windscribe2:/etc/openvpn/custom/`

in the folder put the windscribe 
```
ca.crt
ta.key
default.ovpn
```

set 

```
OPENVPN_PROVIDER=custom
OPENVPN_CONFIG=default
```

**Comment by Sanrax** [comment]
@Pherax, I also solved my issue using the custom config.

I think my method was a bit simpler though. I downloaded a Windscribe .ovpn config from their site's generator, then put it on the computer running docker. Then I mounted the ovpn file on /etc/openvpn/custom/default.ovpn, and ran the container. Transmission WebUI works fine now.

**Comment by elisimpson** [comment]
This issue should be reopened as it's still not working without the custom config workarounds mentioned above.

**Comment by Sanrax** [comment]
> Can we get this change merged into the main docker-transmission-openvpn as it's still using the outdated configs and is therefore broken on Windscribe.

I agree. It should be working with the built-in Windscribe configs, but it only works with a custom config. So, clearly the container needs updating.

**Comment by pkishino** [comment]
no new or updated configs will be merged into the main repo as we will be releasing 4.0 without any configs included in the near future.. @haugene and me are busy with various other things.
to use the configs in THIS repo, you need to use the dev branch of the main container..so not 3.7, not latest, but dev
