### ISSUE TITLE
Hidemyass not supported anymore ?

### ISSUE THREAD

**Issue by rwaeselynck** [haugene/vpn-configs-contrib#195]
### Do you have the latest provider files?

- [X] I have checked that the provider are the latest

### Have you tested the provider files?

- [X] I have tested the provider files

### Can you create a PR for this config?

- [ ] I can create a PR for this

### Provider details

Hi, I'm sorry to bother the community, I use haugene container for years now, and I managed to get it working across the changes made ... until today.
I saw there were some structural updates on the container with a split of providers in another repo, so my issue might be related to that.

Here is the log of my container, that does not start at all now (was working fine a few weeks ago : 

Starting container with revision: 1c6397e565921139f661be4597576e423fb7543e
TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: HIDEMYASS
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for HIDEMYASS. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.MrN1hNQifT
Extracting configs to /tmp/tmp.F5Li2V6NOU
ERROR: Could not find any configs for provider HIDEMYASS in downloaded configs
Cleanup: deleting /tmp/tmp.MrN1hNQifT and /tmp/tmp.F5Li2V6NOU

Here is how I launch my container 

docker run --name=TransmissionVPNdev -d \
-v /volume1/transmission/config:/config \
-v /volume1/transmission/:/data \
-v /volume1/Anime:/data/filebot/output/Anime:rw \
-v /volume1/Movies:/data/filebot/output/Movies:rw \
-v /volume1/TV\ Shows:/data/filebot/output/TV\ Shows:rw \
-v /volume1/Music:/data/filebot/output/Music:rw \
-v /volume1/transmission/resolv.conf:/etc/resolv.conf \
-v /volume1/Downloads:/volume2/Downloads \
-v /volume1/transmission/docker-transmission-openvpn/openvpn/hidemyass:/etc/openvpn/hidemyass/ \
--cap-add=NET_ADMIN --device=/dev/net/tun \
--dns 8.8.8.8 --dns 8.8.4.4 --dns 208.67.222.222 --dns 208.67.220.220 \
--sysctl net.ipv6.conf.all.disable_ipv6=0 \
-e "OPENVPN_PROVIDER=HIDEMYASS" \
-e "OPENVPN_CONFIG=france" \
-e "OPENVPN_USERNAME=MyUserName" \
-e "OPENVPN_PASSWORD=MyPassword" \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e "LOCAL_NETWORK=192.168.1.0/24" \
-e "TRANSMISSION_HOME=/config/transmission-home" \
-e "TRANSMISSION_DOWNLOAD_DIR=/data/filebot/input" \
-e "TRANSMISSION_INCOMPLETE_DIR=/data/incomplete" \
-e "TRANSMISSION_INCOMPLETE_DIR_ENABLED=true" \
-e "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/transmission-docker-postprocess-v1.sh" \
-e "TRANSMISSION_RPC_USERNAME=MyUserName" \
-e "TRANSMISSION_RPC_PASSWORD={dflkflkdlf433ac837a5e6c91e50erere066649c2d09dEr9KlCxaAZ" \
-e "TRANSMISSION_UMASK=0" \
-p 9092:9091 haugene/transmission-openvpn:dev

How can I solve this ?
Do I have to rise the issue on the main repo related to the container itself ?
Thanks for you help

**Comment by pkishino** [comment]
#185

**Comment by rwaeselynck** [comment]
Ok thanks @pkishino
