### ISSUE TITLE
Options error: --ca fails with 'mullvad_ca.crt': No such file or directory (errno=2)

### ISSUE THREAD

**Issue by kushagharahi** [haugene/vpn-configs-contrib#197]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

        - name: OPENVPN_PROVIDER
          value: "MULLVAD"
        - name: OPENVPN_USERNAME

        - name: OPENVPN_PASSWORD

        - name: OPENVPN_OPTS
          value: "--inactive 3600 --ping 10 --ping-exit 60"
        - name: LOCAL_NETWORK

        - name: LOG_TO_STDOUT
          value: "true"
        - name: CREATE_TUN_DEVICE
          value: "false"

### Current Behavior

Without `OPENVPN_CONFIG` defined, the container fails to start with the following error `Options error: --ca fails with 'mullvad_ca.crt': No such file or directory (errno=2)`

### Expected Behavior

Without `OPENVPN_CONFIG` defined, the container starts

### How have you tried to solve the problem?

Adding `OPENVPN_CONFIG`

### Log output

`Options error: --ca fails with 'mullvad_ca.crt': No such file or directory (errno=2)`

### Environment

```markdown
- OS: Ubuntu 20
- Docker: K8s
```

**Comment by pkishino** [comment]
please show the whole log and config.. need to check if it ran the modifier script etc..

**Comment by kushagharahi** [comment]
I'm sorry, for some reason it is now working without `OPENVPN_CONFIG` even though I could not getting it working last night. Unfortunately I don't have logs to provide. I'll run it without `OPENVPN_CONFIG` defined and see if the issue presents itself again.
