### ISSUE TITLE
PIA PORT UPDATER not connecting 

### ISSUE THREAD

**Issue by begunfx** [haugene/vpn-configs-contrib#215]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

`  docker run --cap-add=NET_ADMIN -d \
  --name=transmission \
  -p 9091:9091 \
  -e TRANSMISSION_RPC_USERNAME=**** \
  -e TRANSMISSION_RPC_PASSWORD=***** \
  -e TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true \
  -e LOCAL_NETWORK=192.168.1.0/24 \
  -e OPENVPN_PROVIDER=PIA \
  -e OPENVPN_CONFIG=us_california,us_las_vegas,us_seattle,us_west \
  -e OPENVPN_USERNAME=**None** \
  -e OPENVPN_PASSWORD=**None** \
  -e TZ=America/Los_Angeles \
  -e OPENVPN_OPTS='--inactive 3600 --ping 10 --ping-exit 60' \
  -v /volume1/docker/transmission/data:/data \
  -v /volume1/docker/transmission/config:/config \
  -v /volume1/docker/transmission/config/openvpn-credentials.txt:/config/openvpn-credentials.txt \
  --log-driver json-file \
  --log-opt max-size=10m \
  haugene/transmission-openvpn:dev`

### Current Behavior

If I run the above docker command without the port updater variable disabled:
  -e DISABLE_PORT_UPDATER=true

Then, transmission doesn't seem to connect to any trackers whatsoever.   However, if I include the above environment variable, it runs without issue.  

Please see issue haugene/docker-transmission-openvpn#1570 This is most likely the same issue, but that issue was closed.

### Expected Behavior

I expect transmission and an openVPN connection so I can connect to trackers to download files.

### How have you tried to solve the problem?

I started by following the troubleshooting page - ran through every step and in the end the docker command provided there had Transmission and OpenVPN working correctly.
I slowly added my Docker run to the sample command and found the only difference that caused the failures was not having:
  -e DISABLE_PORT_UPDATER=true

### Log output

I cannot find any logs to provide.  

### HW/SW Environment

```markdown
- OS: Synology DSM 7.1.1
- Docker: latest dev version
```

### Anything else?

My VPN provider is PIA and I'm using US based servers.

**Comment by pkishino** [comment]
This seems to be related to PiA servers that do not support port forwarding.. I’ll take a look at the script and see if I can catch the error and print a message about checking with PIA if the server supports this feature or not

**Comment by begunfx** [comment]
Awesome.  Thank you.

**Comment by pkishino** [comment]
added a simple log update [5113025]
this should better help users understand the problem
