### ISSUE TITLE
VPN.ac OpenVPN configs are out of date

### ISSUE THREAD

**Issue by bergandi** [haugene/vpn-configs-contrib#222]
### Do you have the latest provider files?

- [X] I have checked that the provider are the latest

### Have you tested the provider files?

- [X] I have tested the provider files

### Can you create a PR for this config?

- [X] I can create a PR for this

### Provider details

The provider files are located at: https://vpn.ac/ovpn/ and were updated on 2023-01-09.

**Comment by export-mike** [comment]
is this related to the error: 

```
 ERROR: OVPN: cannot ping https://downloads.nordcdn.com/configs/files, network or internet unavailable. Cannot download NORDVPN configuration files
```

**Comment by ilike2burnthing** [comment]
Why would it have anything to do with NordVPN?

**Comment by globalnomad** [comment]
The certificates for VPN.ac expired and were replaced on Jan 4, 2024. Can these be updated? I'm not the best at this stuff otherwise I'd offer to move everything in myself.

https://vpn.ac/ovpn/
