### ISSUE TITLE
Nordvpn: username/password authent is deprecated

### ISSUE THREAD

**Issue by yongbi85** [haugene/vpn-configs-contrib#224]
### Do you have the latest provider files?

- [X] I have checked that the provider are the latest

### Have you tested the provider files?

- [X] I have tested the provider files

### Can you create a PR for this config?

- [ ] I can create a PR for this

### Provider details

Hello,

Nordvpn has deprecated the basic authent with username/password and you now need service credentials
Could you update the docket to do so and indicate what would be the new environment variable to use
https://support.nordvpn.com/General-info/1653315162/Changes-to-the-login-process-on-third-party-apps-and-routers.htm

**Comment by yongbi85** [comment]
Nevermind, you just need to generate them on your nordvpn dashboard and use them as user and password credentials in your usual environment variables

**Comment by pkishino** [comment]
updated documentation
