### ISSUE TITLE
Maximum option line length (256) exceeded

### ISSUE THREAD

**Issue by domier** [haugene/vpn-configs-contrib#228]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

Created using synology container manager, but here are the environment variables:

CREATE_TUN_DEVICE | true
DROP_DEFAULT_ROUTE | **None**
ENABLE_UFW | false
GLOBAL_APPLY_PERMISSIONS | true
HEALTH_CHECK_HOST | google.com
LOG_TO_STDOUT | false
NORDVPN_COUNTRY | NL
OPENVPN_CONFIG_URL | https://github.com/haugene/vpn-configs-contrib/blob/main/openvpn/nordvpn/configure-openvpn.sh
OPENVPN_OPTS | --inactive 3600 --ping 10 --ping-exit 60
OPENVPN_PROVIDER | NORDVPN
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PEER_DNS | true
PEER_DNS_PIN_ROUTES | true
PGID | **None**
PUID | **None**
REVISION | b33d0fe4c938259a0d4eb844e55468f387456121
SELFHEAL | false
TRANSMISSION_DOWNLOAD_DIR | /data/completed
TRANSMISSION_HOME | /config/transmission-home
TRANSMISSION_INCOMPLETE_DIR | /data/incomplete
TRANSMISSION_RPC_PASSWORD | **None**
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_RPC_USERNAME | **None**
TRANSMISSION_WATCH_DIR | /data/watch
UFW_ALLOW_GW_NET | false
UFW_DISABLE_IPTABLES_REJECT | false
UFW_EXTRA_PORTS | **None**
WEBPROXY_ENABLED | false
WEBPROXY_PASSWORD | **None**
WEBPROXY_PORT | 8118
WEBPROXY_USERNAME | **None**

### Current Behavior

Startup fails with an error Maximum option line length (256) exceeded

### Expected Behavior

Starts sucessfully

### How have you tried to solve the problem?

Transmission had been running successfully for some time, but it seems an update to a newer version caused it to stop working.  After reading the documentation and logs I saw I needed to add OPENVPN_CONFIG_URL and OPENVPN_PROVIDER, but after adding them I was met with the option line length error and not sure how to resolve.  I tried looking for related text inside the vpn config file, but didn't see anything and have run out of ideas (https://github.com/haugene/vpn-configs-contrib/blob/main/openvpn/nordvpn/configure-openvpn.sh)

### Log output

Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121

Creating TUN device /dev/net/tun

Found URL to single OpenVPN config, will download and use it.

Using OpenVPN provider: NORDVPN

Modifying /etc/openvpn/nordvpn/downloaded_config.ovpn for best behaviour in this container

Modification: Point auth-user-pass option to the username/password file

Modification: Change ping options

Modification: Change ca certificate path

Modification: Update/set resolv-retry to 15 seconds

Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop

Modification: Change tls-crypt keyfile path

Modification: Set output verbosity to 3

Modification: Updating status for config failure detection

Setting OpenVPN credentials...

Options error: In /etc/openvpn/nordvpn/downloaded_config.ovpn:1: Maximum option line length (256) exceeded, line starts with {"payload":{"allShortcutsEnabled":false,"fileTree":{"openvpn/nordvpn":{"items":[{"name":"configure-openvpn.sh","path":"openvpn/nordvpn/configure-openvpn.sh","contentType":"file"}],"totalCount":1},"openvpn":{"items":[{"name":"anonine","path":"openvpn/anonin

Use --help for more information.

### Environment

```markdown
- OS: DSM 7.2-64570
- Container Manager: 20.10.23-1413
```

### Anything else?

None

**Comment by ilike2burnthing** [comment]
> I saw I needed to add OPENVPN_CONFIG_URL

You don't.

What you do need is `OPENVPN_USERNAME`, `OPENVPN_PASSWORD`, and https://haugene.github.io/docker-transmission-openvpn/provider-specific/#nordvpn.
