### ISSUE TITLE
Update Windscribe OVPN - New CA

### ISSUE THREAD

**Issue by QuiGonLeong** [haugene/vpn-configs-contrib#23]
## Before creating this request I have:

**REQUIRED**
- [X] Searched for similar [provider requests][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the request as possible
- [X] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
Windscribe
```

### Where are the configs?

**REQUIRED**
```txt
Providers website
```
### Additional context

*Optional*

``` Due to some changes by Windscribe CA the current OVPN configs aren't working.
https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222

VERIFY ERROR: depth=1, error=unable to get local issuer certificate: C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=Windscribe Node CA X2, serial=1

OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed ```
<!-- check *Preview Issue* before submitting -->

**Comment by smshr** [comment]
is there any workaround for this, till the certificates get updated in the image?

**Comment by shamowfski** [comment]
> is there any workaround for this, till the certificates get updated in the image?

I manually edited the openvpn config I needed to use.   So I ran docker exec -it transmission /bin/bash, edited /etc/openvpn/windscribe/<theconfigiuse> and replaced it with the new one from this repository, then ran pkill openvpn.  It's 100% a bandaid.

**Comment by nibrwr** [comment]
Here's a config file from Windscribe, if it helps (renamed to .txt for upload)

[Windscribe-Atlanta-Mountain.txt](https://github.com/haugene/vpn-configs-contrib/files/6865375/Windscribe-Atlanta-Mountain.txt)

**Comment by smshr** [comment]
> I manually edited the openvpn config I needed to use. So I ran docker exec -it transmission /bin/bash, edited /etc/openvpn/windscribe/<theconfigiuse> and replaced it with the new one from this repository, then ran pkill openvpn. It's 100% a bandaid.

maybe that works on docker, but I am in kubernetes and I tried following, it didn't work:
`kubectl -n apps exec --stdin --tty transmission-67bdbbb85d-9z5hf -- /bin/bash`

after `pkill openvpn`, kubernetes overwrites the changed ovpn file.

**Comment by shamowfski** [comment]
In theory you could clone the image repo, update the config files manually and build the image yourself.  Or, clone the config repo, and mount the locally cloned config repo to /etc/openvpn/windscribe (respecting the folder structure, and also, this might not work with kubernetes?).

**Comment by smshr** [comment]
> In theory you could clone the image repo, update the config files manually and build the image yourself. Or, clone the config repo, and mount the locally cloned config repo to /etc/openvpn/windscribe (respecting the folder structure, and also, this might not work with kubernetes?).

It should work, I think. However, in the meantime I tried CUSTOM configuration and it worked. It is well documented here: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
The only downside is that I am for now restricted to one location, earlier I could provide a list of locations and any one of them will be randomly selected at the time of image startup.

**Comment by Fizpop91** [comment]
Having the same issue, and I don't think I have the docker knowledge to apply the workaround mentioned above, but ill give it a bash :D

**Comment by ochompsky** [comment]
commenting here as i need this as well, am watching this thread.

**Comment by pkishino** [comment]
feel free to provide a PR with the fix, then I can review and merge this

**Comment by ochompsky** [comment]
> feel free to provide a PR with the fix, then I can review and merge this

it looks like it was already merged into https://github.com/haugene/vpn-configs-contrib/pull/21 

i'm just not sure how it makes it's way to the `docker-transmission-openvpn` repo frm here.

**Comment by pkishino** [comment]
You need to be on the dev branch of the main repo for now to get these
updates..

**Comment by pkishino** [comment]
I take it this can be closed as new windscribe configs were merged into here ?

**Comment by QuiGonLeong** [comment]
> You need to be on the dev branch of the main repo for now to get these updates..

When will this be merged in the main repo?

**Comment by pkishino** [comment]
when 4.0 is released..which will release when we have the time.
