### ISSUE TITLE
Privado VPN Configs outdated

### ISSUE THREAD

**Issue by jeremyaltman** [haugene/vpn-configs-contrib#230]
### Do you have the latest provider files?

- [X] I have checked that the provider are the latest

### Have you tested the provider files?

- [X] I have tested the provider files

### Can you create a PR for this config?

- [ ] I can create a PR for this

### Provider details

Privado has updated their VPN configs and taken down many old servers and removed their DNS records. Of the 19 servers they now have for the DFW area, only one still remains in this project and it's extremely over-provisioned and slow. Looking at many other locations and this seems to be pretty widespread.

Latest configs available at: https://privadovpn.com/apps/ovpn_configs.zip 

Configs in this repo for privado haven't been updated in over 2 years.

### Anything else?

Looks like this script just needs to be run and then commit the new configs to the repo. Would probably be advisable to delete the existing configs prior to running the update.

https://github.com/haugene/vpn-configs-contrib/blob/main/openvpn/privado/updateConfigs.sh

**Comment by Twit123** [comment]
Any update on this as all London servers have changed name so none of the configs work anymore.
