### ISSUE TITLE
VPNUNLIMITED issue with manual adding

### ISSUE THREAD

**Issue by aevans0001** [haugene/vpn-configs-contrib#231]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

version: '2.1'
services:
 transmission-openvpn:
    volumes:
        - ./transmission/config:/config
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1000
        - PGID=1000
        - CREATE_TUN_DEVICE=true
        - GLOBAL_APPLY_PERMISSIONS=true
        - OPENVPN_PROVIDER=VPNUNLIMITED
        # OPENVPN_CONFIG=
        - GITHUB_CONFIG_SOURCE_REPO=XXX/docker-transmission-openvpn
        # VPNUNLIMITED_COUNTRY=CA
        # VPNUNLIMITED_CATEGORY=legacy_p2p
        # VPNUNLIMITED_PROTOCOL=udp
        - OPENVPN_USERNAME=XXX
        - OPENVPN_PASSWORD=XXX
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.1.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - DNS=8.8.8.8,8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9090:9090 #Transmission
    restart: always
    image: haugene/transmission-openvpn

### Current Behavior

attempts tp download from Downloading configs from https://github.com/XXX/../../main.zip

gets a 404

### Expected Behavior

Downloads from here https://github.com/XXX/../../master.zip

### How have you tried to solve the problem?

I have emailed VPNUNLIMITED to update their config files and cipher but this is not yet my problem with manual

### Log output

Cleanup: deleting /tmp/tmp.J1GezWHSEG and /tmp/tmp.kIRZU0CDU1
Starting container with revision: 1103172c3288b7de681e2fb7f1378314f17f66cf
TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: VPNUNLIMITED
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for VPNUNLIMITED. Defaulting to external config
Downloading configs from https://github.com/XXX/../../main.zip into /tmp/tmp.deRxipuKMg
curl: (22) The requested URL returned error: 404

### Environment

```markdown
- OS: Ubuntu 23.04
- Docker: 24.05
```

### Anything else?

I do have my own ovpm

**Comment by pkishino** [comment]
One comment.. why no /data mount??

**Comment by aevans0001** [comment]
sorry i cleared that out, i do have one, i just didnt think it was pertinent to my issue.  I can edit if i need to

**Comment by aevans0001** [comment]
All good thanks
