### ISSUE TITLE
VPNUNLIMITED out 

### ISSUE THREAD

**Issue by Geneocide** [haugene/vpn-configs-contrib#233]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

PATH, OPENVPN_USERNAME and OPENVPN_PASSWORD not pictured
![image](https://github.com/haugene/vpn-configs-contrib/assets/1274287/70fe3532-ca08-4d90-a973-8e929f0e704a)

### Current Behavior

I'll put the screenshot of the logs below. the actual error is ca md too weak. Seems like the VPNUNLIMITED configurations are no good.

### Expected Behavior

connect to Open VPN

### How have you tried to solve the problem?

I tried several different VPNUNLIMITED ovpn files present. I also tried modifying the ovpn with various suggestions to try to reduce error reporting, but I don't think I'm doing it right.

### Log output

![image](https://github.com/haugene/vpn-configs-contrib/assets/1274287/1a22b4a8-731a-4986-901c-9d52a4bac7e5)

### Environment

```markdown
- OS: Synology DSM 7.2-64570 Update 1
- Docker:
```

**Comment by Scoobdriver** [comment]
Do you have `tls-cipher=DEFAULT:@SECLEVEL=0 ` in your config file ?

See [https://github.com/qdm12/gluetun/issues/1432](url)

**Comment by Geneocide** [comment]
No. I don't know where the config file I need to edit is, I guess.

**Comment by Scoobdriver** [comment]
This would be your .ovpn file . I had this issue as vpnunlimtted have not upgraded their ciphers (I think ) so this line reduces the security level I believe. If you do a search there is a thread on it.

**Comment by Geneocide** [comment]
ok. Yeah, I think I tried this but it said it didn't recognize the command, so I assume I did it wrong. Oh, just figured it out. I had to do it in the tls-cipher "DEFAULT:@SECLEVEL=0" format. I'm a novice at this stuff so I need more detailed instructions than are easy to find often time. So, sorry for the clutter if this is unhelpful post. And thanks for the assist.
