### ISSUE TITLE
Windscribe phasing out OpenVPN compression -- requires configuration change

### ISSUE THREAD

**Issue by smshr** [haugene/vpn-configs-contrib#24]
## Before creating this request I have:

**REQUIRED**
- [x] Searched for similar [provider requests][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the request as possible
- [x] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
WINDSCRIBE
```

### Where are the configs?

**REQUIRED**
```txt
Providers website
```
### Additional context

*Optional*

Refer: https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222
Windscribe has started phasing out OpenVPN compression, this requires a small change in the existing config files.
Line 13, i.e. `comp-lzo` in the Windscribe [config files](https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/windscribe) need to be removed.

**Comment by smshr** [comment]
In this new OpenVPN config resitory, I think, it is line 15, i.e. `compress lzo` in the Windscribe [config files](https://github.com/haugene/vpn-configs-contrib/tree/main/openvpn) that needs to be removed.

**Comment by pkishino** [comment]
please submit a PR if you want this fixed

**Comment by pkishino** [comment]
@wilmardo any chance you could check this as you contributed the last windscribe update?thanks

**Comment by wilmardo** [comment]
Yes on it, expect a PR in a couple of minutes :)

**Comment by pkishino** [comment]
Cool, thanks
