### ISSUE TITLE
Support for Mozilla VPN

### ISSUE THREAD

**Issue by cocrico** [haugene/vpn-configs-contrib#26]
## Before creating this request I have:

**REQUIRED**
- [X] Searched for similar [provider requests][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the request as possible
- [X] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```
Mozilla
```

### Where are the configs?

**REQUIRED**
```
I can't find any. It's possible I don't know what I'm doing.
Website here: https://www.mozilla.org/en-US/products/vpn/
```
### Additional context

```
There is a fork: https://github.com/mozilla/openvpn
I'm not good enough at any of this but would be amazing if Mozilla was added to the base VPN configs.
```

**Comment by pkishino** [comment]
had a quick look and yeah, can't see any configs we can use..
