### ISSUE TITLE
NordVPN fails due to their API no longer working

### ISSUE THREAD

**Issue by mjuopperi** [haugene/vpn-configs-contrib#264]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to the container/transmission?

- [X] I have checked the container repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

```
version: '3.2'
services:
  deluge-openvpn:
    volumes:
      - '/media/data/docker/torrent/downloads/:/download'
      - '/data/docker/torrent/docker-deluge-openvpn/config/:/config'
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=xxxxxx
      - OPENVPN_PASSWORD=xxxxxx
      - NORDVPN_COUNTRY=FI
      - NORDVPN_PROTOCOL=tcp
      - NORDVPN_CATEGORY=legacy_p2p
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/16
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - '8112:8112'
    image: ebrianne/docker-deluge-openvpn
    restart: unless-stopped
```

### Current Behavior

Container fails to find proper config file because the NordVPN api no longer works.
I talked with their chat support and it is intentional.

e.g. https://api.nordvpn.com/v1/servers/groups (Should show `429 Too Many Requests` or another error or not respond)

### Expected Behavior

Container finds openvpn profile

### How have you tried to solve the problem?

1. Started from scratch with latest versions
2. Figured out the issue from logs
3. Went through the [code](https://github.com/haugene/vpn-configs-contrib/blob/main/openvpn/nordvpn/configure-openvpn.sh)
4. Contacted NordVPN support

### Log output

```
Sat Dec 30 10:55:36 2023 [start-vpn] Configuring OPENVPN
Sat Dec 30 10:55:36 2023 [start-vpn] Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
2023-12-30 10:55:36 Checking curl installation
2023-12-30 10:55:36 Removing existing configs
2023-12-30 10:55:36 Selecting the best server...
parse error: Invalid numeric literal at line 1, column 7
2023-12-30 10:55:36 Searching for technology: openvpn_tcp
parse error: Invalid numeric literal at line 1, column 7
2023-12-30 10:55:36 Unable to find a server with the specified parameters, using any recommended server
parse error: Invalid numeric literal at line 1, column 7
2023-12-30 10:55:36 Best server :
2023-12-30 10:55:36 Downloading config: default.ovpn
2023-12-30 10:55:36 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/.tcp443.ovpn
2023-12-30 10:55:36 Selecting the best server...
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
2023-12-30 10:55:36 Searching for technology: openvpn_tcp
parse error: Invalid numeric literal at line 1, column 7
2023-12-30 10:55:36 Unable to find a server with the specified parameters, using any recommended server
parse error: Invalid numeric literal at line 1, column 7
2023-12-30 10:55:36 Best server :
2023-12-30 10:55:36 Downloading config: .ovpn
2023-12-30 10:55:36 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/.tcp443.ovpn
2023-12-30 10:55:36 Checking line endings
2023-12-30 10:55:36 Updating configs for docker-deluge-openvpn
Sat Dec 30 10:55:45 2023 [start-vpn] No VPN configuration provided. Using default.
Modifying /etc/openvpn/nordvpn/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Sat Dec 30 10:55:45 2023 [start-vpn] Setting OpenVPN credentials...
Sat Dec 30 10:55:45 2023 [ufw-enable] Got local network 172.28.0.1 and CIDR  on interface eth0
Sat Dec 30 10:55:45 2023 [ufw-enable] Firewall script executed with tun0 /etc/openvpn/nordvpn/default.ovpn
adding route to local network 192.168.1.0/16 via 172.28.0.1 dev eth0
Error: Invalid prefix for given prefix length.
Sat Dec 30 10:55:45 2023 [start-vpn] Starting openvpn
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.4)
Use --help for more information.
```

- `parse error: Invalid numeric literal at line 1, column 7` 
   This is a `jq` error due to the API returning a HTML error page rather than JSON
- `2023-12-30 10:55:36 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/.tcp443.ovpn`   
   The value for server ends up empty, thus `.tcp443.ovpn`

### Environment

```markdown
- OS: Fedora release 33
- Docker: 20.10.12
```

**Comment by ilike2burnthing** [comment]
Working fine here, both the container and accessing https://api.nordvpn.com/v1/servers/groups in browser.

No idea what support told you, but either they misunderstood you, you misunderstood them, or they were talking crap. As far as I'm aware they use their API for their own software, so it would make zero sense for them just to disable it.

Tried changing your DNS to `1.1.1.1` and/or `8.8.8.8`?

**Comment by mjuopperi** [comment]
You're right. I just tried with another IP address and it works. I'll talk with their support again.
