### ISSUE TITLE
Windscribe Connections are now failing

### ISSUE THREAD

**Issue by adamcodes716** [haugene/vpn-configs-contrib#27]
## Before creating this request I have:

**REQUIRED**
- [x ] Searched for similar [provider requests][pi] and [container issues][ci]
- [ x] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [ x] Tried to add as much relevant information to the request as possible
- [x ] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
Windscribe
```

### Where are the configs?

```txt
https://windscribe.com/getconfig/openvpn
```
### Additional context

*Optional*

``` Hi, the ovpn files for Windscribe are outdated and no longer functioning (TLS errors when the VPN is trying to connect). Could they be replaced in a newer version?
New configurations can be downloaded from: https://windscribe.com/getconfig/openvpn ```
<!-- check *Preview Issue* before submitting -->

**Comment by adamcodes716** [comment]
More background information on their change:

https://blog.windscribe.com/openvpn-security-improvements-and-changes-7b04ea49222

**Comment by pkishino** [comment]
this has already been fixed.. please use search and fill out the template properly..
