### ISSUE TITLE
ProtonVPN is out of date, and also other concerns

### ISSUE THREAD

**Issue by DaGeek247** [haugene/vpn-configs-contrib#30]
## Before creating this request I have:

**REQUIRED**
- [x] Searched for similar [provider requests][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the request as possible
- [X] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
ProtonVPN
```

### Where are the configs?

**REQUIRED**
```txt
http://dageek247.com/wordpress/wp-content/uploads/2021/08/protonvpn.zip
```
### Additional context

ProtonVPN claims to block p2p traffic on most of their servers, and allow it on a specific few. https://protonvpn.com/support/p2p-vpn-redirection/ I have found that this block is not complete - it doesn't work for the server I have been using for the past month or on the free version i used at a friends house one time. It is entirely possible that this block doesn't work at all based on my limited testing.

However, in the spirit of using the service as intended, I am providing a file with all the ProtonVPN servers that explicitly support p2p traffic. One thing of note is that ProtonVPN has three tiers of access to their servers. Free, Basic, and Plus. I have access to files for Basic and Free, but not Plus. If someone could download the Plus p2p servers that would also be helpful. Also note that the free plan doesn't have access to any of the servers listed as allowing p2p, so I have just included all of them. This new free list has more servers than the current one. It is all sorted in the zip file, but can be merged into a single folder pretty easily.

Issues with the current protonvpn config files that this file fixes:

- the protonvpn website has the wrong names for some of their files by default
- the current config files are incomplete (it doesn't have all the p2p servers, or all of the actual servers)
- the current config files include p2p servers and non-p2p servers

For ProtonVPN, you can also pick a server that will pick the best target server in a specific country, or you can pick a specific server yourself. These are country configurations and standard configurations. Country will choose a server for you and standard is a specific server connection. I have separated these two different types into two subfolders.

I used sed to [switch specific bits of text](https://unix.stackexchange.com/questions/112023/how-can-i-replace-a-string-in-a-files?newreg=63655f028ac04f11bbf861c7bba8db9f) in the ovpn files:

- I replaced my username with 'protonusername'. These config files mention the downloader's username for things like their ad/malware dns blocker by default, which are helpful, but don't actually need a specific username.
- I replaced 'cipher AES-256-CBC' with '--data-ciphers-fallback AES-256-CBC'. ProtonVPN works without the switch, but openvpn wont write nastygrams in the logs if you change this.
- I replaced 'auth-user-pass' with 'auth-user-pass /config/openvpn-credentials.txt'.
- I also commented out the up/down lines by replacing 'up' with '#up' and 'down' with '#down'.

As far as I can tell, these are all the changes that needed to be made to the ovpn files before they work as a default protonvpn config library.

**Comment by pkishino** [comment]
Hey, if you create a PR where you replace the old Proton files with your new ones that would be great, much easier to review.thanks

**Comment by Unrepentant-Atheist** [comment]
See https://github.com/haugene/vpn-configs-contrib/pull/64 for new p2p only config files.

**Comment by pkishino** [comment]
Merged in
