### ISSUE TITLE
WARNING: cannot stat file 'uk1-TCP-443-tls.key': No such file or directory (errno=2) transmission    | Options error: --tls-crypt fails with 'uk1-TCP-443-tls.key': No such file or directory (errno=2)

### ISSUE THREAD

**Issue by tuzun89** [haugene/vpn-configs-contrib#43]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    volumes:
        - /mnt/data:/mnt/data
       - /config/openvpn-credentials.txt:/config/openvpn-credentials.txt
    environment:
        - PUID=1000
        - PGID=1000
        - CONFIG_MOD_CA_CERTS=false
        - GITHUB_CONFIG_SOURCE_REPO=tuzun89/vpn-configs-contrib
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=celo
        - OPENVPN_CONFIG=uk1-TCP-443
        - OPENVPN_USERNAME=***
        - OPENVPN_PASSWORD=***
        - WEBPROXY_ENABLED=false
        - TRANSMISSION_DOWNLOAD_DIR=/mnt/data/downloads
        - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
        - TRANSMISSION_SEED_QUEUE_ENABLED=true
        - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
        - LOCAL_NETWORK=192.168.0.0/24
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - "9091:9091"
    restart: unless-stopped

### Current Behavior

cannot connect to vpn service
infinite loop

### Expected Behavior

direct connection to vpn service

### How have you tried to solve the problem?

attempted to some potential solutions using advice on the issues page.

### Log output

Starting container with revision: 8744279e2cd191486ca5ae21e8e051b7b1000b71
Creating TUN device /dev/net/tun
Using OpenVPN provider: CELO
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for CELO. Defaulting to external config
Downloading configs from https://github.com/tuzun89/vpn-configs-contrib/archive/main.zip into /tmp/tmp.c3sKmQGthj
Extracting configs to /tmp/tmp.Stn2pJrlZd
Found configs for CELO in /tmp/tmp.Stn2pJrlZd/vpn-configs-contrib-main/openvpn/celo, will replace current content in /etc/openvpn/celo
Cleanup: deleting /tmp/tmp.c3sKmQGthj and /tmp/tmp.Stn2pJrlZd
Starting OpenVPN using config uk1-TCP-443.ovpn
Modifying /etc/openvpn/celo/uk1-TCP-443.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Setting OpenVPN credentials...
adding route to local network 192.168.0.0/24 via 172.18.0.1 dev eth0
Tue Sep  7 23:35:44 2021 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
Tue Sep  7 23:35:44 2021 WARNING: cannot stat file 'uk1-TCP-443-tls.key': No such file or directory (errno=2)
Options error: --tls-crypt fails with 'uk1-TCP-443-tls.key': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.

### Environment

```markdown
- OS: Ubuntu Server 20.04
- Docker: Latest
```

**Comment by pkishino** [comment]
I had a quick look at your vpn config and they are not correct..
either you need to update this script
https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/modify-openvpn-config.sh
so it also modifies your location of the key files (just like it does CA cert location) or you need to update the ovpn file

**Comment by tuzun89** [comment]
> I had a quick look at your vpn config and they are not correct..
> either you need to update this script
> https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/modify-openvpn-config.sh
> so it also modifies your location of the key files (just like it does CA cert location) or you need to update the ovpn file

Many thanks for looking into this.  I've referenced the 2no additional files (CA and tls-key) within the ovpn file.  It think there's some progress now but I still can't connect.  It states the following in the log:

> Starting container with revision: 8744279e2cd191486ca5ae21e8e051b7b1000b71
> Creating TUN device /dev/net/tun
> Using OpenVPN provider: CELO
> Running with VPN_CONFIG_SOURCE auto
> No bundled config script found for CELO. Defaulting to external config
> Downloading configs from https://github.com/tuzun89/vpn-configs-contrib/archive/main.zip into /tmp/tmp.d1J8geSzR3
> Extracting configs to /tmp/tmp.PSRKM04kPt
> Found configs for CELO in /tmp/tmp.PSRKM04kPt/vpn-configs-contrib-main/openvpn/celo, will replace current content in /etc/openvpn/celo
> Cleanup: deleting /tmp/tmp.d1J8geSzR3 and /tmp/tmp.PSRKM04kPt
> Starting OpenVPN using config uk1-TCP-443.ovpn
> Modifying /etc/openvpn/celo/uk1-TCP-443.ovpn for best behaviour in this container
> Modification: Point auth-user-pass option to the username/password file
> Modification: Change ca certificate path
> Modification: Change ping options
> Setting OpenVPN credentials...
> adding route to local network 192.168.0.0/24 via 172.18.0.1 dev eth0
> Wed Sep  8 11:49:36 2021 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
> Wed Sep  8 11:49:36 2021 WARNING: file '/etc/openvpn/celo/uk1-TCP-443-tls.key' is group or others accessible
> Wed Sep  8 11:49:36 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Wed Sep  8 11:49:37 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Wed Sep  8 11:49:43 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

If you have any ideas, I would really appreciate your advise.

Best regards,

**Comment by haugene** [comment]
Good case for improving our `modify-openvpn-config.sh` script.

So, two things to improve here. The first is that we don't fix the paths for the tls key. And I believe that the second issue is the `resolv-retry infinite` line.

> --resolv-retry n
If hostname resolve fails for --remote, retry resolve for n seconds before failing.Set n to "infinite" to retry indefinitely.
By default, --resolv-retry infinite is enabled. You can disable by setting n=0.

So my guess is that you're having DNS issues, which is common, and that it just retries and never gives up. If it had given up I think you would see a more descriptive error.

I'll make some changes to the script, are you up for testing a bit? :smile:

**Comment by haugene** [comment]
I was wrong, but still I think my resolv-retry argument is valid. There's another thing in your configs `verb 0` that hides useful logs from us.

> --verb n
Set output verbosity to n (default=1). Each level shows all info from the previous levels. Level 3 is recommended if you want a good summary of what's happening without being swamped by output

I'm implementing switch to 3 as well now.

**Comment by haugene** [comment]
Allright. I've committed a fix to the dev-branch. Can you try pulling the :dev tag and test? You will probably still not be able to connect, but it will print why at least.

Would also be interesting to see if it would work with the original config as you committed it, before modifying it manually: https://github.com/tuzun89/vpn-configs-contrib/commit/77831c42de3f52ff975965b2b55976a966f362b3#diff-7d787fc7c23d2f3e8efe359503f6eb096dd1d624c67d63b2159ec9478a04a5ae

Since I've already run this locally I can spoil a bit here on why it's failing:

```
Creating TUN device /dev/net/tun
Using OpenVPN provider: CELO
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for CELO. Defaulting to external config
Downloading configs from https://github.com/tuzun89/vpn-configs-contrib/archive/main.zip into /tmp/tmp.KYkHbOZOnG
Extracting configs to /tmp/tmp.GBmlczxTAJ
Found configs for CELO in /tmp/tmp.GBmlczxTAJ/vpn-configs-contrib-main/openvpn/celo, will replace current content in /etc/openvpn/celo
Cleanup: deleting /tmp/tmp.KYkHbOZOnG and /tmp/tmp.GBmlczxTAJ
Starting OpenVPN using config uk1-TCP-443.ovpn
Modifying /etc/openvpn/celo/uk1-TCP-443.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Found existing OPENVPN credentials at /config/openvpn-credentials.txt
adding route to local network 192.168.0.0/16 via 172.20.0.1 dev eth0
Wed Sep  8 14:57:53 2021 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
Wed Sep  8 14:57:53 2021 WARNING: file '/etc/openvpn/celo/uk1-TCP-443-tls.key' is group or others accessible
Wed Sep  8 14:57:53 2021 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
Wed Sep  8 14:57:53 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Wed Sep  8 14:57:53 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Wed Sep  8 14:57:53 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Sep  8 14:57:53 2021 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Sep  8 14:57:53 2021 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Sep  8 14:57:53 2021 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Sep  8 14:57:53 2021 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Sep  8 14:57:53 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]51.89.182.233:443
Wed Sep  8 14:57:53 2021 Socket Buffers: R=[131072->131072] S=[16384->16384]
Wed Sep  8 14:57:53 2021 Attempting to establish TCP connection with [AF_INET]51.89.182.233:443 [nonblock]
Wed Sep  8 14:57:54 2021 TCP connection established with [AF_INET]51.89.182.233:443
Wed Sep  8 14:57:54 2021 TCP_CLIENT link local: (not bound)
Wed Sep  8 14:57:54 2021 TCP_CLIENT link remote: [AF_INET]51.89.182.233:443
Wed Sep  8 14:57:54 2021 TLS: Initial packet from [AF_INET]51.89.182.233:443, sid=9ec6975d 30eb5479
Wed Sep  8 14:57:54 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Sep  8 14:57:54 2021 VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: CN=internal-ca, C=GB, L=London, O=CELO
Wed Sep  8 14:57:54 2021 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Wed Sep  8 14:57:54 2021 TLS_ERROR: BIO read tls_read_plaintext error
Wed Sep  8 14:57:54 2021 TLS Error: TLS object -> incoming plaintext read error
Wed Sep  8 14:57:54 2021 TLS Error: TLS handshake failed
Wed Sep  8 14:57:54 2021 Fatal TLS error (check_tls_errors_co), restarting
Wed Sep  8 14:57:54 2021 SIGUSR1[soft,tls-error] received, process restarting
Wed Sep  8 14:57:54 2021 Restart pause, 5 second(s)
```

**Comment by tuzun89** [comment]
Wow, this is incredibly detailed - many thanks for this.  I've already changed the ovpn file to 'verb=3' and noticed a very similar log output.  

I will now carry out what you've asked with the dev tag and with the original ovpn config - will come back with the results asap.

**Comment by haugene** [comment]
Just pushed another change. I see that we get a SIGUSR1 signal. OpenVPN has an option to remap it to SIGTERM so that it exits instead of restarts.

Since we're running in a container we want it to die instead of having OpenVPN retrying in a loop. Then we can control it with `restart: unless-stopped (or always)` or similar in Docker

**Comment by tuzun89** [comment]
This is what I get with the :dev tag and original config:

> Starting container with revision: d580138e43217772fbc4d25aa3f47bea6068a332
> Creating TUN device /dev/net/tun
> Using OpenVPN provider: CELO
> Running with VPN_CONFIG_SOURCE auto
> No bundled config script found for CELO. Defaulting to external config
> Downloading configs from https://github.com/tuzun89/vpn-configs-contrib/archive/main.zip into /tmp/tmp.8EYgeLbI8a
> Extracting configs to /tmp/tmp.tqMUx9aHjT
> Found configs for CELO in /tmp/tmp.tqMUx9aHjT/vpn-configs-contrib-main/openvpn/celo, will replace current content in /etc/openvpn/celo
> Cleanup: deleting /tmp/tmp.8EYgeLbI8a and /tmp/tmp.tqMUx9aHjT
> Starting OpenVPN using config uk1-TCP-443.ovpn
> Modifying /etc/openvpn/celo/uk1-TCP-443.ovpn for best behaviour in this container
> Modification: Point auth-user-pass option to the username/password file
> Modification: Change ping options
> Modification: Update/set resolv-retry to 15 seconds
> Modification: Change tls-crypt keyfile path
> Modification: Set output verbosity to 3
> Found existing OPENVPN credentials at /config/openvpn-credentials.txt
> adding route to local network 192.168.0.0/16 via 172.18.0.1 dev eth0
> Wed Sep  8 15:13:55 2021 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
> Options error: --ca fails with 'uk1-TCP-443-ca.crt': No such file or directory (errno=2)
> Wed Sep  8 15:13:55 2021 WARNING: file '/etc/openvpn/celo/uk1-TCP-443-tls.key' is group or others accessible
> Wed Sep  8 15:13:55 2021 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
> Options error: Please correct these errors.
> Use --help for more information.

I thought the 'verb=0' ovpn file overrides your changes, so I tried the config with a 'verb=3' change only as well but get the same log.

**Comment by haugene** [comment]
Hmmm...

> Modifying /etc/openvpn/celo/uk1-TCP-443.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3


And not:
>Modification: Change ca certificate path

Are you running with `CONFIG_MOD_CA_CERTS=0` or something?

**Comment by tuzun89** [comment]
Oops, yeah I was running with 'false'.  Actual log:

> Starting container with revision: d580138e43217772fbc4d25aa3f47bea6068a332
> Creating TUN device /dev/net/tun
> Using OpenVPN provider: CELO
> Running with VPN_CONFIG_SOURCE auto
> No bundled config script found for CELO. Defaulting to external config
> Downloading configs from https://github.com/tuzun89/vpn-configs-contrib/archive/main.zip into /tmp/tmp.TGksGDcULQ
> Extracting configs to /tmp/tmp.4F8AIKmxCm
> Found configs for CELO in /tmp/tmp.4F8AIKmxCm/vpn-configs-contrib-main/openvpn/celo, will replace current content in /etc/openvpn/celo
> Cleanup: deleting /tmp/tmp.TGksGDcULQ and /tmp/tmp.4F8AIKmxCm
> Starting OpenVPN using config uk1-TCP-443.ovpn
> Modifying /etc/openvpn/celo/uk1-TCP-443.ovpn for best behaviour in this container
> Modification: Point auth-user-pass option to the username/password file
> Modification: Change ca certificate path
> Modification: Change ping options
> Modification: Update/set resolv-retry to 15 seconds
> Modification: Change tls-crypt keyfile path
> Modification: Set output verbosity to 3
> Found existing OPENVPN credentials at /config/openvpn-credentials.txt
> adding route to local network 192.168.0.0/16 via 172.21.0.1 dev eth0
> Wed Sep  8 15:30:49 2021 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
> Wed Sep  8 15:30:49 2021 WARNING: file '/etc/openvpn/celo/uk1-TCP-443-tls.key' is group or others accessible
> Wed Sep  8 15:30:49 2021 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
> Wed Sep  8 15:30:49 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
> Wed Sep  8 15:30:49 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
> Wed Sep  8 15:30:49 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Wed Sep  8 15:30:49 2021 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> Wed Sep  8 15:30:49 2021 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> Wed Sep  8 15:30:49 2021 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> Wed Sep  8 15:30:49 2021 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> Wed Sep  8 15:30:49 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]51.89.182.233:443
> Wed Sep  8 15:30:49 2021 Socket Buffers: R=[131072->131072] S=[16384->16384]
> Wed Sep  8 15:30:49 2021 Attempting to establish TCP connection with [AF_INET]51.89.182.233:443 [nonblock]
> Wed Sep  8 15:30:50 2021 TCP connection established with [AF_INET]51.89.182.233:443
> Wed Sep  8 15:30:50 2021 TCP_CLIENT link local: (not bound)
> Wed Sep  8 15:30:50 2021 TCP_CLIENT link remote: [AF_INET]51.89.182.233:443
> Wed Sep  8 15:30:50 2021 TLS: Initial packet from [AF_INET]51.89.182.233:443, sid=c96275ff 05ace134
> Wed Sep  8 15:30:50 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Wed Sep  8 15:30:50 2021 VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: CN=internal-ca, C=GB, L=London, O=CELO
> Wed Sep  8 15:30:50 2021 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
> Wed Sep  8 15:30:50 2021 TLS_ERROR: BIO read tls_read_plaintext error
> Wed Sep  8 15:30:50 2021 TLS Error: TLS object -> incoming plaintext read error
> Wed Sep  8 15:30:50 2021 TLS Error: TLS handshake failed
> Wed Sep  8 15:30:50 2021 Fatal TLS error (check_tls_errors_co), restarting
> Wed Sep  8 15:30:50 2021 SIGUSR1[soft,tls-error] received, process restarting
> Wed Sep  8 15:30:50 2021 Restart pause, 5 second(s)
> Wed Sep  8 15:30:55 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Wed Sep  8 15:30:55 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]51.89.182.233:443
> Wed Sep  8 15:30:55 2021 Socket Buffers: R=[131072->131072] S=[16384->16384]
> Wed Sep  8 15:30:55 2021 Attempting to establish TCP connection with [AF_INET]51.89.182.233:443 [nonblock]
> Wed Sep  8 15:30:56 2021 TCP connection established with [AF_INET]51.89.182.233:443
> Wed Sep  8 15:30:56 2021 TCP_CLIENT link local: (not bound)
> Wed Sep  8 15:30:56 2021 TCP_CLIENT link remote: [AF_INET]51.89.182.233:443
> Wed Sep  8 15:30:56 2021 TLS: Initial packet from [AF_INET]51.89.182.233:443, sid=c754461a 11c1b7e4
> Wed Sep  8 15:30:56 2021 VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: CN=internal-ca, C=GB, L=London, O=CELO
> Wed Sep  8 15:30:56 2021 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
> Wed Sep  8 15:30:56 2021 TLS_ERROR: BIO read tls_read_plaintext error
> Wed Sep  8 15:30:56 2021 TLS Error: TLS object -> incoming plaintext read error
> Wed Sep  8 15:30:56 2021 TLS Error: TLS handshake failed
> Wed Sep  8 15:30:56 2021 Fatal TLS error (check_tls_errors_co), restarting
> Wed Sep  8 15:30:56 2021 SIGUSR1[soft,tls-error] received, process restarting
> Wed Sep  8 15:30:56 2021 Restart pause, 5 second(s)

**Comment by tuzun89** [comment]
Could it be related to the time?  I just noticed that the time on the logs are incorrect however TZ=Europe/London.  I guess does not into account the British Summer Time.

It seems feasible that a handshake failure can occur due to a mismatch in the timings given?

**Comment by haugene** [comment]
I feel it's a stretch. If timestamps were changing and bouncing around maybe they would have a sanity check for it. But what timezone a client is in should not matter.

I think this is the critical line:
> Wed Sep 8 15:30:50 2021 VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: CN=internal-ca, C=GB, L=London, O=CELO

Are they using self signed certificates? That's a security risk in that case. You should get their certificate so you can add that explicitly in that case. But it's weird. VPN companies are usually focused on security.

Doesn't look like you can tell OpenVPN to ignore it... Not that you'd want to, other than to test.
https://www.reddit.com/r/PrivateInternetAccess/comments/ido9hl/openvpn_service_complains_about_selfsigned_cert/

You're sure that you have the latest and greatest, or at least "matching" keys to the config you're trying to use?

**Comment by tuzun89** [comment]
So, I've changed the ovpn file to another self-contained one from the vpn providers website.  The ovpn file contains the key and cert - it still doesn't work and here is the log:

> Starting container with revision: d580138e43217772fbc4d25aa3f47bea6068a332
> Creating TUN device /dev/net/tun
> Using OpenVPN provider: CELO
> Running with VPN_CONFIG_SOURCE auto
> No bundled config script found for CELO. Defaulting to external config
> Downloading configs from https://github.com/tuzun89/vpn-configs-contrib/archive/main.zip into /tmp/tmp.VGO0SLSjXF
> Extracting configs to /tmp/tmp.QDKuhBIeA8
> Found configs for CELO in /tmp/tmp.QDKuhBIeA8/vpn-configs-contrib-main/openvpn/celo, will replace current content in /etc/openvpn/celo
> Cleanup: deleting /tmp/tmp.VGO0SLSjXF and /tmp/tmp.QDKuhBIeA8
> Starting OpenVPN using config London TCP 443.ovpn
> Modifying /etc/openvpn/celo/London TCP 443.ovpn for best behaviour in this container
> Modification: Point auth-user-pass option to the username/password file
> Modification: Change ca certificate path
> Modification: Change ping options
> Modification: Update/set resolv-retry to 15 seconds
> Modification: Change tls-crypt keyfile path
> Modification: Set output verbosity to 3
> Found existing OPENVPN credentials at /config/openvpn-credentials.txt
> adding route to local network 192.168.0.0/16 via 172.25.0.1 dev eth0
> Wed Sep  8 19:11:40 2021 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
> Wed Sep  8 19:11:40 2021 Unrecognized option or missing or extra parameter(s) in /etc/openvpn/celo/London TCP 443.ovpn:11: block-outside-dns (2.4.7)
> Wed Sep  8 19:11:40 2021 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
> Wed Sep  8 19:11:40 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
> Wed Sep  8 19:11:40 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
> Wed Sep  8 19:11:40 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Wed Sep  8 19:11:40 2021 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> Wed Sep  8 19:11:40 2021 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> Wed Sep  8 19:11:40 2021 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> Wed Sep  8 19:11:40 2021 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> Wed Sep  8 19:11:40 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]51.89.182.233:443
> Wed Sep  8 19:11:40 2021 Socket Buffers: R=[131072->131072] S=[16384->16384]
> Wed Sep  8 19:11:40 2021 Attempting to establish TCP connection with [AF_INET]51.89.182.233:443 [nonblock]
> Wed Sep  8 19:11:41 2021 TCP connection established with [AF_INET]51.89.182.233:443
> Wed Sep  8 19:11:41 2021 TCP_CLIENT link local: (not bound)
> Wed Sep  8 19:11:41 2021 TCP_CLIENT link remote: [AF_INET]51.89.182.233:443
> Wed Sep  8 19:11:41 2021 TLS: Initial packet from [AF_INET]51.89.182.233:443, sid=33572b61 5d282736
> Wed Sep  8 19:11:41 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Wed Sep  8 19:11:41 2021 VERIFY OK: depth=1, CN=internal-ca, C=GB, L=London, O=CELO
> Wed Sep  8 19:11:41 2021 VERIFY KU OK
> Wed Sep  8 19:11:41 2021 Validating certificate extended key usage
> Wed Sep  8 19:11:41 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
> Wed Sep  8 19:11:41 2021 VERIFY EKU OK
> Wed Sep  8 19:11:41 2021 VERIFY OK: depth=0, CN=uk1.celo.net, C=GB, L=London, O=CELO
> Wed Sep  8 19:11:41 2021 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
> Wed Sep  8 19:11:41 2021 [uk1.celo.net] Peer Connection Initiated with [AF_INET]51.89.182.233:443
> Wed Sep  8 19:11:42 2021 SENT CONTROL [uk1.celo.net]: 'PUSH_REQUEST' (status=1)
> Wed Sep  8 19:11:42 2021 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 94.140.14.14,dhcp-option DNS 94.140.15.15,redirect-gateway def1,redirect-gateway ipv6,tun-ipv6,route-gateway 10.200.0.1,topology subnet,ping 10,ping-restart 60,ifconfig-ipv6 2402:9400:1000:2::1000/64 2402:9400:1000:2::1,ifconfig 10.200.0.2 255.255.255.0,peer-id 0'
> Wed Sep  8 19:11

:42 2021 OPTIONS IMPORT: timers and/or timeouts modified
Wed Sep  8 19:11:42 2021 OPTIONS IMPORT: --ifconfig/up options modified
Wed Sep  8 19:11:42 2021 OPTIONS IMPORT: route options modified
Wed Sep  8 19:11:42 2021 OPTIONS IMPORT: route-related options modified
Wed Sep  8 19:11:42 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Sep  8 19:11:42 2021 OPTIONS IMPORT: peer-id set
Wed Sep  8 19:11:42 2021 OPTIONS IMPORT: adjusting link_mtu to 1626
Wed Sep  8 19:11:42 2021 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Wed Sep  8 19:11:42 2021 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Wed Sep  8 19:11:42 2021 ROUTE_GATEWAY 172.25.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:19:00:02
Wed Sep  8 19:11:42 2021 GDG6: remote_host_ipv6=n/a
Wed Sep  8 19:11:42 2021 ROUTE6: default_gateway=UNDEF
Wed Sep  8 19:11:42 2021 TUN/TAP device tun0 opened
Wed Sep  8 19:11:42 2021 TUN/TAP TX queue length set to 100
Wed Sep  8 19:11:42 2021 /sbin/ip link set dev tun0 up mtu 1500
Wed Sep  8 19:11:42 2021 /sbin/ip addr add dev tun0 10.200.0.2/24 broadcast 10.200.0.255
Wed Sep  8 19:11:42 2021 /sbin/ip -6 addr add 2402:9400:1000:2::1000/64 dev tun0
RTNETLINK answers: Permission denied
Wed Sep  8 19:11:42 2021 Linux ip -6 addr add failed: external program exited with error status: 2
Wed Sep  8 19:11:42 2021 Exiting due to fatal error

**Comment by tuzun89** [comment]
I think I managed to get it working with the following lines in the docker compose file:

> sysctls:
>         - net.ipv6.conf.all.disable_ipv6=0

Thanks very much for your efforts.

**Comment by pkishino** [comment]
Great. Is the key personal to your account or provider wide? If it is then
if you remake it slightly so that anyone can easily mount their key file
instead then I’d welcome a PR to this repo to add the provider (please
update documentation as well then ;) )

**Comment by tuzun89** [comment]
Awesome, I will prepare the PR and update the docs ASAP.
