### ISSUE TITLE
Some torrents get stuck at Magnetized transfer - retrieving metadata 0%

### ISSUE THREAD

**Issue by Marelebone** [haugene/vpn-configs-contrib#49]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

version: '3.3'

  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - 9091:9091
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/media/docker/transmission-vpn:/data
      - /home/media/docker/shared:/shared
      - /media/drive/data/torrents:/data/torrents
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=pXXXXXXXX
      - OPENVPN_PASSWORD=XXXXXXXXX
      - OPENVPN_CONFIG=switzerland
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.xxx.0/24
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT_ENABLED=false
      - TRANSMISSION_DOWNLOAD_DIR=/data/torrents
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_WATCH_DIR_ENABLED=false
      - TRANSMISSION_HOME=/data/transmission-home
      - TRANSMISSION_RENAME_PARTIAL_FILES=false
      - TRANSMISSION_PEX_ENABLED=false
      - TRANSMISSION_DHT_ENABLED=false
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/extract_torrent.sh
      - TRANSMISSION_CACHE_SIZE_MB=10

### Current Behavior

Most torrents download perfectly fine using Haugene's transmission-vpn. Since approx. one month however some torrents get stuck at Magnetized transfer - retrieving metadata 0%. This problem seems only to appear when using public trackers.

I tested these torrents on my laptop with qbitorrent and connecting to PIA and it works just fine. So it seems for certain torrents transmission can't connect to peers.

I am not sure if it has something to do with ipv6 `WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.` nor do I know how to fix this error.

### Expected Behavior

Download of all torrents if seeders are available.

### How have you tried to solve the problem?

1) Restarted docker container
2) Restarted server
3) Changed DNS in .yml from 1.1.1.1/1.0.0.1 to 8.8.8.8/8.8.4.4

### Log output

transmission-vpn    | STARTING TRANSMISSION
transmission-vpn    | Provider PIA has a script for automatic port forwarding. Will run it now.
transmission-vpn    | If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true
transmission-vpn    | Transmission startup script complete.
transmission-vpn    | Mon Sep  6 12:04:26 2021 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
transmission-vpn    | Mon Sep  6 12:04:26 2021 Initialization Sequence Completed
transmission-vpn    | Running functions for token based port fowarding
transmission-vpn    | Reserved Port: 25848  Mon Sep  6 12:04:33 CEST 2021
transmission-vpn    | transmission auth not required
transmission-vpn    | waiting for transmission to become responsive
transmission-vpn    | transmission became responsive
transmission-vpn    |    6   100%    6.22 MB  Done         0.0     0.0    0.0  Idle         
transmission-vpn    | Sum:          110.5 GB               0.0     0.0
transmission-vpn    | setting transmission port to 25848
transmission-vpn    | localhost:9091/transmission/rpc/ responded: "success"
transmission-vpn    | Checking port...
transmission-vpn    | Port is open: Yes
transmission-vpn    | #######################
transmission-vpn    |         SUCCESS        
transmission-vpn    | #######################

In the transmission.log file i often see these messages:
[2021-09-06 13:10:23.266] Couldn't connect socket 120 to 2a05:4f44:b13:4e00::2, port 32247 (errno 99 - Cannot assign requested address) (net.c:288)

Please let me know if further logs are required

### Environment

```markdown
- OS: Ubuntu 20.04
- Docker: 20.10.7
- VPN Provider: PrivateInternetAccess
```

**Comment by pkishino** [comment]
@technowhizz does your PR #47 fix this? just tagging for reference.

**Comment by technowhizz** [comment]
> @technowhizz does your PR #47 fix this? just tagging for reference.

Unfortunately not

**Comment by pkishino** [comment]
oh, too bad..
I suggest first to validate dns settings in /etc/resolv.conf inside container.. and to try to ping the hostname of the tracker to see if that works.

**Comment by technowhizz** [comment]
I tried a different config file and its now working. Turns out only some purevpn servers support torrenting/p2p
