### ISSUE TITLE
please add cyberghostvpn to the container

### ISSUE THREAD

**Issue by perforatedpaper** [haugene/vpn-configs-contrib#6]

**Comment by pkishino** [comment]
No link to files or other items added.. please update with details or will  close

**Comment by haugene** [comment]
@perforatedpaper We need a link to a zip file containing all the configs for this provider in order to add it

**Comment by e2950** [comment]
cyberghost files
[transmission_openvpn(3).zip](https://github.com/haugene/vpn-configs-contrib/files/10298272/transmission_openvpn.3.zip)
