### ISSUE TITLE
PIA Port forwarding failed to be created since last docker dev image version (Oct 21, 2021 at 2:54 am)

### ISSUE THREAD

**Issue by jscoys** [haugene/vpn-configs-contrib#76]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [ ] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

  transmission:
    image: haugene/transmission-openvpn:dev
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    network_mode: mybridge
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - 9091:9091
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media_sharing/Downloads/Transmission/:/data
    environment:
      - CREATE_TUN_DEVICE=false
      - OPENVPN_PROVIDER=PIA
      - PIA_OPENVPN_CONFIG_BUNDLE=openvpn
      - OPENVPN_CONFIG=sweden
      - OPENVPN_USERNAME=xxxxxx
      - OPENVPN_PASSWORD=xxxxxx
      - WEBPROXY_ENABLED=false
      - GLOBAL_APPLY_PERMISSIONS=false
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=1000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_DOWN=14000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=500
      - TRANSMISSION_LPD_ENABLED=true
      - TRANSMISSION_UTP_ENABLED=true
      - TRANSMISSION_PEX_ENABLED=true
      - TRANSMISSION_DHT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=2
      - start-added-torrents=true

### Current Behavior

Port forwarding failed to open, marked as closed into the network tab of transmission.

### Expected Behavior

Having a port opened correctly and reachable with status "Open" in network tab, as the previous dev docker image.

### How have you tried to solve the problem?

Can't coming back on the dev version, but was working before.

### Log output

STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true
Transmission startup script complete.
Thu Oct 21 20:54:23 2021 /sbin/ip route add 195.246.120.22/32 via 172.18.0.1
Thu Oct 21 20:54:23 2021 /sbin/ip route add 0.0.0.0/1 via 10.19.112.1
Thu Oct 21 20:54:23 2021 /sbin/ip route add 128.0.0.0/1 via 10.19.112.1
Thu Oct 21 20:54:23 2021 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
Thu Oct 21 20:54:23 2021 Initialization Sequence Completed
Running functions for token based port fowarding
curl: (28) Operation timed out after 15000 milliseconds with 0 bytes received
Thu Oct 21 20:54:44 EDT 2021: getSignature error
{ "status": "ERROR", "message": "Login failed!" }
the has been a fatal_error
parse error: Invalid numeric literal at EOF at line 1, column 3
parse error: Invalid numeric literal at EOF at line 1, column 3
Thu Oct 21 20:54:46 EDT 2021: bindPort error
{ "status": "", "message": "bad signature" }
the has been a fatal_error
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
   5     0%    5.83 MB  Unknown      0.0     0.0    0.0  Idle         
Sum:           7.44 GB               0.0     0.0
setting transmission port to
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response
#######################
        SUCCESS
#######################
Port:
Expiration Thu Oct 21 00:00:00 EDT 2021
#######################
Entering infinite while loop
Every 15 minutes, check port status
60 day port reservation reached
Getting a new one
curl: (28) Operation timed out after 15001 milliseconds with 0 bytes received
Thu Oct 21 20:55:12 EDT 2021: getSignature error
{ "status": "ERROR", "message": "Login failed!" }
the has been a fatal_error
parse error: Invalid numeric literal at EOF at line 1, column 3
parse error: Invalid numeric literal at EOF at line 1, column 3
Thu Oct 21 20:55:13 EDT 2021: bindPort error
{ "status": "", "message": "bad signature" }
the has been a fatal_error
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
   5     0%    5.83 MB  Unknown      0.0     0.0    0.0  Idle         
Sum:           7.44 GB               0.0     0.0
setting transmission port to
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response

### Environment

```markdown
- OS: Centos 8
- Docker: Docker version 20.10.7, build f0df350
```

**Comment by dcardin** [comment]
I have the same problem with port forwarding with the latest image. Using 3.7.1 works perfectly.
