### ISSUE TITLE
TorGuard Australian servers have switched hostname

### ISSUE THREAD

**Issue by lachlanmacphee** [haugene/vpn-configs-contrib#8]
## Before creating this request I have:

**REQUIRED**
- [x] Searched for similar [provider requests][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the request as possible
- [x] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
Torguard
```

### Where are the configs?

**REQUIRED**
```txt
https://torguard.net/tgconf.php?action=vpn-openvpnconfig
```
### Additional context

*Optional*
```I believe that the previous 2 Australian servers in the OpenVPN config have been switched to only one located in Sydney, Australia for TorGuard. I have had numerous issues gaining a connection, and I think this can be attributed to the change in hostname. Where previously the two servers were au1.torguard.com:1912 and au2.torguard.com:1912 , the new server appears to be au.torguard.com:1912 according to the OpenVPN config file downloaded for Sydney. I may be completely off here, but I have spent hours on this problem and struggled to get a custom config file in to test (new to Docker, Linux, and all of that, so please be patient with me!). Hopefully this will come easier with the 4.0 update in the works. ```

**Comment by lachlanmacphee** [comment]
Don't know what I'm doing wrong here. Followed the template the first time and the bot still didn't like it...

**Comment by pkishino** [comment]
No, you didnt follow the template.. please read through and check the boxes as required..

**Comment by lachlanmacphee** [comment]
> 
> 
> No, you didnt follow the template.. please read through and check the boxes as required..

Please see the first revision of the post, in which I typed X in the necessary boxes and it still failed to publish, hence my reply:

"Followed the template the first time and the bot still didn't like it..."

**Comment by pkishino** [comment]
yes..if there are spaces then it's not a checked box, if you check preview it will show when the box is checked

**Comment by lachlanmacphee** [comment]
> 
> 
> yes..if there are spaces then it's not a checked box (even a comment in the template regarding this), if you check preview it will show when the box is checked

Apologies, I missed the spaces part of that. Silly me. Thanks for your help

**Comment by pkishino** [comment]
Regarding using a custom ovpn please tell me what the problem is as the steps are in the documentation here for how to use it.
