### ISSUE TITLE
Update for TrustZone .ovpn files

### ISSUE THREAD

**Issue by bamojr** [haugene/vpn-configs-contrib#9]
## Before creating this request I have:

**REQUIRED**
- [X] Searched for similar [provider requests][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the provider, custom provider, troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the request as possible
- [X] Agreed that my request will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Which provider?

**REQUIRED**
```txt
TrustZone
```

### Where are the configs?

**REQUIRED**
```txt
https://trust.zone/downloads/ovpn.zip
```
### Additional context

*Optional*

``` Per the update on their website: https://trust.zone/post/big-security-update-trustzone-vpn```
![image](https://user-images.githubusercontent.com/24615890/116718489-02b5c980-a9a8-11eb-8fd3-8dcd597a2127.png)

**Comment by pkishino** [comment]
Not sure why the bot closed the original issue, but did you test the new files as custom and they work now? No more problem?

**Comment by bamojr** [comment]
@pkishino yup, I was able to use the new TZ ovpn file for the New York server and was able to get it working, so I think the new ovpn.zip should be good to be applied to the whole project!

**Comment by Fagerinfoco** [comment]
I am having a serious problem with this. I also use Trust.Zone.  I pulled the configuration today, so this is not an issue of the old versions of the .ovpn files.  I am initiating through docker-compose, but i am obviously missing something. When i launch i get this error:

Using OpenVPN provider: TRUSTZONE
2 servers found in OPENVPN_CONFIG, Trust.Zone-United-States-Colorado chosen randomly
Supplied config Trust.Zone-United-States-Colorado.ovpn could not be found.

I broke it down and am starting this stack separate from my normal docker-compose file by running it through the editor in portainer.

version: "3.6"
services:
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 109.236.87.2
      - 23.237.56.98
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/openvpn/custom:/config
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/Downloads:/data/watch
      - ${USERDIR}/Downloads/completed:/data/completed
      - ${USERDIR}/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=TRUSTZONE
      - OPENVPN_USERNAME=*****
      - OPENVPN_PASSWORD=*****
      - OPENVPN_CONFIG=Trust.Zone-United-States-MID,Trust.Zone-United-States-Colorado
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=****
      - TRANSMISSION_RPC_USERNAME=****
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true



I would really appreciate any help with this

**Comment by bamojr** [comment]
@Fagerinfoco,  I don't think the OVPN files have yet been updated for Trust.Zone in the project yet. Using the OPENVPN_PROVIDER=TRUSTZONE won't work if that is the case. Trying looking at the documentation here to get a single custom ovpn file working: https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_local_set_of_ovpn_files_from_provider

**Comment by pkishino** [comment]
@Fagerinfoco 
First of all, the new files are not added to the report yet, there is no pull request made for them, so you need to use custom provider..
Second, your mounts look strange..
Why you mounting localtime? That’s hasn’t been needed in quite a while. TZ fixed this.
Second, you are mounting /config to a local volume point, why?
Follow the link above to use custom, rest looks ok

**Comment by Fagerinfoco** [comment]
First, thank you both for the quick response. the mount points look odd because i'm following a guide that might be a little out of date. I changed the volumes and followed the directions given:
    volumes:
      - ${USERDIR}/docker/transmission/trustzone/:/etc/openvpn/custom/
      - ${USERDIR}/docker/transmission-vpn:/data
The ovpn and .cer files are in {$USERDIR}/docker/transmission/trustzone. removes the localtime mount.
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_USERNAME=****
      - OPENVPN_PASSWORD=****
      - OPENVPN_CONFIG=Trust.Zone-United-States-MID
the ovpn is named exactly the same as the OPENVPN_CONFIG. The CA is built into the ovpn file and the auth-user-pass has been adjusted to read "auth-user-pass /etc/openvpn/custom/openvpn-credentials.txt". That folder exists in both the host OS as well as the mount point in the container. Still getting "Supplied config Trust.Zone-United-States-MID.ovpn could not be found."

**Comment by pkishino** [comment]
can you share the log when you use custom and also a ls of the
/etc/openvpn/custom/ folder please?

**Comment by Fagerinfoco** [comment]
logs:
Starting container with revision: fccd0ca9062110d77ab08ac385962207d84319c3
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: CUSTOM
Supplied config Trust.Zone-United-States-MID.ovpn could not be found.
Your options for this provider are:
NB: Remember to not specify .ovpn as part of the config name.

Starting container with revision: fccd0ca9062110d77ab08ac385962207d84319c3
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: CUSTOM
Supplied config Trust.Zone-United-States-MID.ovpn could not be found.
Your options for this provider are:
NB: Remember to not specify .ovpn as part of the config name.

(then it just repeats)


ls of /etc/openvpn/custom:
drwxr-xr-x 2 root  root  4096 May 28 19:23 .
drwxr-xr-x 5 root  root  4096 May 28 19:06 ..
-rw-r--r-- 1 root  root     9 May 28 19:08 openvpn-credentials.txt
-rw-rw-r-- 1 {myuser} {myuser} 3156 May 28 19:12 Trust.Zone-United-States-Colorado_ca.cer
-rw-rw-r-- 1 {myuser} {myuser} 7849 May 28 19:23 Trust.Zone-United-States-Colorado.ovpn
-rw-rw-r-- 1 {myuser} {myuser} 3156 May 28 19:12 Trust.Zone-United-States-MID_ca.cer
-rw-rw-r-- 1 {myuser} {myuser} 7850 May 28 19:23 Trust.Zone-United-States-MID.ovpn

had a thought...should those files be chownd to root?

**Comment by pkishino** [comment]
As they have read it should be fine.. but worth a try..
I’m wondering if the naming could be an issue.. could you try renaming it
to default.ovpn instead? Then you can also drop the ovpn config line..

**Comment by Fagerinfoco** [comment]
getting somewhere i think. New error from logs:

Starting container with revision: fccd0ca9062110d77ab08ac385962207d84319c3
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/24 via 172.23.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/custom/default.ovpn
Use --help for more information.

commented out the OPENVPN_CONFIG line. in both /etc/openvpn/custom (host OS) and {$USERDIR}/docker/transmission/trustzone (mount point in container) there is a default.ovpn (rw-rw-r--)

**Comment by pkishino** [comment]
Hmm, error opening.. then I would try to change owner to root first..
otherwise, file corrupted?

**Comment by Fagerinfoco** [comment]
i tried something else. i uncommented the OPENVPN_CONFIG line, but left it as a custom setup. I'm getting a different error:

Starting container with revision: fccd0ca9062110d77ab08ac385962207d84319c3
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: CUSTOM
Supplied config Trust.Zone-United-States-MID.ovpn could not be found.
Your options for this provider are:
NB: Remember to not specify .ovpn as part of the config name.

indicates to me it's looking in a specific place for this file, but i don't have the file in the right location. Where should the .ovpn file be located (either in the host os or in the container volumes) for this to work?

**Comment by pkishino** [comment]
You did check the wiki entry right? Then it should work..

**Comment by Fagerinfoco** [comment]
yes. i replaced
             - /volume1/docker/transmission/ipvanish/:/etc/openvpn/custom/
in the example with 
     - ${USERDIR}/docker/transmission/trustzone/:/etc/openvpn/custom/
for my system which has the following files in it:
drwxrwxr-x+ 2 root root 4096 May 29 06:55 .
drwxrwxr-x+ 3 root root 4096 May 29 05:36 ..
-rw-rw-r--+ 1 root root 7862 May 29 06:55 default.ovpn
-rw-r--r--+ 1 root root    9 May 29 05:42 openvpn-credentials.txt
-rw-rw-r--+ 1 root root 3156 May 29 05:42 Trust.Zone-United-States-Colorado_ca.cer
-rw-rw-r--+ 1 root root 7849 May 29 05:42 Trust.Zone-United-States-Colorado.ovpn
-rw-rw-r--+ 1 root root 3156 May 29 05:42 Trust.Zone-United-States-MID_ca.cer
-rw-rw-r--+ 1 root root 7862 May 29 05:48 Trust.Zone-United-States-MID.ovpn

**Comment by pkishino** [comment]
please check now that #17 has been merged
